---
title: "BoxPlot-b1-N30"
author: "Yi"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.width = 5, fig.height = 5)
options(knitr.kable.NA = '')
library(knitr)
library(kableExtra)
```



### EXP0.2-1

```{r, fig.width = 10, fig.height = 5}


load("exp0.2/N30/HR1_p0.8.RData")
cv   <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv8  <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)


load("exp0.2/N30/HR1_p0.6.RData")
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv6 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)


load("exp0.2/N30/HR1_p0.4.RData")
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv4 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)


load("exp0.2/N30/HR1_p0.2.RData")
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv2 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)


cv <- rbind(cv8, cv6, cv4, cv2)
cv

```


### EXP0.2-2

```{r, fig.width = 10, fig.height = 5}

load("exp0.2/N30/HR2_p0.8.RData")
cv   <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv8  <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)


load("exp0.2/N30/HR2_p0.6.RData")
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv6 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)


load("exp0.2/N30/HR2_p0.4.RData")
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv4 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)


load("exp0.2/N30/HR2_p0.2.RData")
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv2 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)


cv <- rbind(cv8, cv6, cv4, cv2)
cv


```


### EXP0.5-1

```{r, fig.width = 10, fig.height = 5}


load("exp0.5/N30/HR1_p0.8.RData")
cv   <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv8  <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)


load("exp0.5/N30/HR1_p0.6.RData")
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv6 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)


load("exp0.5/N30/HR1_p0.4.RData")
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv4 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)


load("exp0.5/N30/HR1_p0.2.RData")
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv2 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)


cv <- rbind(cv8, cv6, cv4, cv2)
cv

```


### EXP0.5-2

```{r, fig.width = 10, fig.height = 5}

load("exp0.5/N30/HR2_p0.8.RData")
cv   <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv8  <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)


load("exp0.5/N30/HR2_p0.6.RData")
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv6 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)


load("exp0.5/N30/HR2_p0.4.RData")
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv4 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)


load("exp0.5/N30/HR2_p0.2.RData")
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv2 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)


cv <- rbind(cv8, cv6, cv4, cv2)
cv


```


### LN1-1

```{r, fig.width = 10, fig.height = 5}


load("LN1/N30/HR1_p0.8.RData")
cv   <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv8  <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)


load("LN1/N30/HR1_p0.6.RData")
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv6 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)


load("LN1/N30/HR1_p0.4.RData")
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv4 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)


load("LN1/N30/HR1_p0.2.RData")
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv2 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)


cv <- rbind(cv8, cv6, cv4, cv2)
cv

```


### LN1-2

```{r, fig.width = 10, fig.height = 5}

load("LN1/N30/HR2_p0.8.RData")
cv   <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv8  <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)


load("LN1/N30/HR2_p0.6.RData")
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv6 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)


load("LN1/N30/HR2_p0.4.RData")
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv4 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)


load("LN1/N30/HR2_p0.2.RData")
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv2 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)


cv <- rbind(cv8, cv6, cv4, cv2)
cv


```

### U13-1

```{r, fig.width = 10, fig.height = 5}


load("U13/N30/HR1_p0.8.RData")
cv   <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv8  <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)


load("U13/N30/HR1_p0.6.RData")
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv6 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)


load("U13/N30/HR1_p0.4.RData")
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv4 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)


load("U13/N30/HR1_p0.2.RData")
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv2 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)


cv <- rbind(cv8, cv6, cv4, cv2)
cv

```


### U13-2

```{r, fig.width = 10, fig.height = 5}

load("U13/N30/HR2_p0.8.RData")
cv   <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv8  <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)


load("U13/N30/HR2_p0.6.RData")
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv6 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)


load("U13/N30/HR2_p0.4.RData")
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv4 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)


load("U13/N30/HR2_p0.2.RData")
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv2 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)


cv <- rbind(cv8, cv6, cv4, cv2)
cv


```