---
title: "BoxPlot-b1-N20"
author: "Yi"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.width = 5, fig.height = 5)
options(knitr.kable.NA = '')
library(knitr)
library(kableExtra)
```



### EXP0.2-1

```{r, fig.width = 10, fig.height = 5}

p <- seq(0.8, 0.2, -0.2)

load("exp0.2/N20/HR1_p0.8.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med8 <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv   <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv8  <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)
pro  <- matrix(DATA[12,], ncol = 3, byrow = TRUE)
pro8 <- sapply(1:3, function(i) mean(pro[,i], na.rm = TRUE))
dim(DATA) <- c(13, 3, dim(DATA)[2]/3)
MED <- apply(DATA, 1:2, function(x) median(x, na.rm = TRUE))
rownames(MED) <- c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3", "b", "sauc", "S/N/p", "conv")
# MED

load("exp0.2/N20/HR1_p0.6.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med6  <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv6 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)
pro  <- matrix(DATA[12,], ncol = 3, byrow = TRUE)
pro6 <- sapply(1:3, function(i) mean(pro[,i], na.rm = TRUE))
dim(DATA) <- c(13, 3, dim(DATA)[2]/3)
MED <- apply(DATA, 1:2, function(x) median(x, na.rm = TRUE))
rownames(MED) <- c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3", "b", "sauc", "S/N/p", "conv")
# MED

load("exp0.2/N20/HR1_p0.4.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med4  <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv4 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)
pro  <- matrix(DATA[12,], ncol = 3, byrow = TRUE)
pro4 <- sapply(1:3, function(i) mean(pro[,i], na.rm = TRUE))
dim(DATA) <- c(13, 3, dim(DATA)[2]/3)
MED <- apply(DATA, 1:2, function(x) median(x, na.rm = TRUE))
rownames(MED) <- c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3", "b", "sauc", "S/N/p", "conv")
# MED

load("exp0.2/N20/HR1_p0.2.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med2  <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv2 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)
pro  <- matrix(DATA[12,], ncol = 3, byrow = TRUE)
pro2 <- sapply(1:3, function(i) mean(pro[,i], na.rm = TRUE))
dim(DATA) <- c(13, 3, dim(DATA)[2]/3)
MED <- apply(DATA, 1:2, function(x) median(x, na.rm = TRUE))
rownames(MED) <- c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3", "b", "sauc", "S/N/p", "conv")
# MED

x1 <- rbind(med8, med6, med4, med2)


```

### EXP0.2-2

```{r, fig.width = 10, fig.height = 5}


load("exp0.2/N20/HR2_p0.8.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med8 <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv8 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)
pro  <- matrix(DATA[12,], ncol = 3, byrow = TRUE)
pro8 <- sapply(1:3, function(i) mean(pro[,i], na.rm = TRUE))
dim(DATA) <- c(13, 3, dim(DATA)[2]/3)
MED <- apply(DATA, 1:2, function(x) median(x, na.rm = TRUE))
rownames(MED) <- c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3", "b", "sauc", "S/N/p", "conv")
# MED

load("exp0.2/N20/HR2_p0.6.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med6  <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv6 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)
pro  <- matrix(DATA[12,], ncol = 3, byrow = TRUE)
pro6 <- sapply(1:3, function(i) mean(pro[,i], na.rm = TRUE))
dim(DATA) <- c(13, 3, dim(DATA)[2]/3)
MED <- apply(DATA, 1:2, function(x) median(x, na.rm = TRUE))
rownames(MED) <- c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3", "b", "sauc", "S/N/p", "conv")
# MED

load("exp0.2/N20/HR2_p0.4.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med4  <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv4 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)
pro  <- matrix(DATA[12,], ncol = 3, byrow = TRUE)
pro4 <- sapply(1:3, function(i) mean(pro[,i], na.rm = TRUE))
dim(DATA) <- c(13, 3, dim(DATA)[2]/3)
MED <- apply(DATA, 1:2, function(x) median(x, na.rm = TRUE))
rownames(MED) <- c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3", "b", "sauc", "S/N/p", "conv")
# MED

load("exp0.2/N20/HR2_p0.2.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med2  <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv2 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)
pro  <- matrix(DATA[12,], ncol = 3, byrow = TRUE)
pro2 <- sapply(1:3, function(i) mean(pro[,i], na.rm = TRUE))
dim(DATA) <- c(13, 3, dim(DATA)[2]/3)
MED <- apply(DATA, 1:2, function(x) median(x, na.rm = TRUE))
rownames(MED) <- c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3", "b", "sauc", "S/N/p", "conv")
# MED

x2 <- rbind(med8, med6, med4, med2)

```

### EXP0.5-1

```{r, fig.width = 10, fig.height = 5}


load("exp0.5/N20/HR1_p0.8.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med8 <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv8 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)
pro  <- matrix(DATA[12,], ncol = 3, byrow = TRUE)
pro8 <- sapply(1:3, function(i) mean(pro[,i], na.rm = TRUE))
dim(DATA) <- c(13, 3, dim(DATA)[2]/3)
MED <- apply(DATA, 1:2, function(x) median(x, na.rm = TRUE))
rownames(MED) <- c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3", "b", "sauc", "S/N/p", "conv")
# MED

load("exp0.5/N20/HR1_p0.6.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med6  <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv6 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)
pro  <- matrix(DATA[12,], ncol = 3, byrow = TRUE)
pro6 <- sapply(1:3, function(i) mean(pro[,i], na.rm = TRUE))
dim(DATA) <- c(13, 3, dim(DATA)[2]/3)
MED <- apply(DATA, 1:2, function(x) median(x, na.rm = TRUE))
rownames(MED) <- c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3", "b", "sauc", "S/N/p", "conv")
# MED

load("exp0.5/N20/HR1_p0.4.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med4  <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv4 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)
pro  <- matrix(DATA[12,], ncol = 3, byrow = TRUE)
pro4 <- sapply(1:3, function(i) mean(pro[,i], na.rm = TRUE))
dim(DATA) <- c(13, 3, dim(DATA)[2]/3)
MED <- apply(DATA, 1:2, function(x) median(x, na.rm = TRUE))
rownames(MED) <- c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3", "b", "sauc", "S/N/p", "conv")
# MED

load("exp0.5/N20/HR1_p0.2.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med2  <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv2 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)
pro  <- matrix(DATA[12,], ncol = 3, byrow = TRUE)
pro2 <- sapply(1:3, function(i) mean(pro[,i], na.rm = TRUE))
dim(DATA) <- c(13, 3, dim(DATA)[2]/3)
MED <- apply(DATA, 1:2, function(x) median(x, na.rm = TRUE))
rownames(MED) <- c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3", "b", "sauc", "S/N/p", "conv")
# MED

x3 <- rbind(med8, med6, med4, med2)

```

### EXP0.5-2

```{r, fig.width = 10, fig.height = 5}


load("exp0.5/N20/HR2_p0.8.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med8 <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv8 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)
pro  <- matrix(DATA[12,], ncol = 3, byrow = TRUE)
pro8 <- sapply(1:3, function(i) mean(pro[,i], na.rm = TRUE))
dim(DATA) <- c(13, 3, dim(DATA)[2]/3)
MED <- apply(DATA, 1:2, function(x) median(x, na.rm = TRUE))
rownames(MED) <- c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3", "b", "sauc", "S/N/p", "conv")
# MED

load("exp0.5/N20/HR2_p0.6.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med6  <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv6 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)
pro  <- matrix(DATA[12,], ncol = 3, byrow = TRUE)
pro6 <- sapply(1:3, function(i) mean(pro[,i], na.rm = TRUE))
dim(DATA) <- c(13, 3, dim(DATA)[2]/3)
MED <- apply(DATA, 1:2, function(x) median(x, na.rm = TRUE))
rownames(MED) <- c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3", "b", "sauc", "S/N/p", "conv")
# MED

load("exp0.5/N20/HR2_p0.4.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med4  <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv4 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)
pro  <- matrix(DATA[12,], ncol = 3, byrow = TRUE)
pro4 <- sapply(1:3, function(i) mean(pro[,i], na.rm = TRUE))
dim(DATA) <- c(13, 3, dim(DATA)[2]/3)
MED <- apply(DATA, 1:2, function(x) median(x, na.rm = TRUE))
rownames(MED) <- c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3", "b", "sauc", "S/N/p", "conv")
# MED

load("exp0.2/N20/HR2_p0.2.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med2  <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv2 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)
pro  <- matrix(DATA[12,], ncol = 3, byrow = TRUE)
pro2 <- sapply(1:3, function(i) mean(pro[,i], na.rm = TRUE))
dim(DATA) <- c(13, 3, dim(DATA)[2]/3)
MED <- apply(DATA, 1:2, function(x) median(x, na.rm = TRUE))
rownames(MED) <- c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3", "b", "sauc", "S/N/p", "conv")
# MED

x4 <- rbind(med8, med6, med4, med2)

```

### LN1-1

```{r, fig.width = 10, fig.height = 5}


load("LN1/N20/HR1_p0.8.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med8 <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv8 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)
pro  <- matrix(DATA[12,], ncol = 3, byrow = TRUE)
pro8 <- sapply(1:3, function(i) mean(pro[,i], na.rm = TRUE))
dim(DATA) <- c(13, 3, dim(DATA)[2]/3)
MED <- apply(DATA, 1:2, function(x) median(x, na.rm = TRUE))
rownames(MED) <- c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3", "b", "sauc", "S/N/p", "conv")
# MED

load("LN1/N20/HR1_p0.6.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med6  <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv6 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)
pro  <- matrix(DATA[12,], ncol = 3, byrow = TRUE)
pro6 <- sapply(1:3, function(i) mean(pro[,i], na.rm = TRUE))
dim(DATA) <- c(13, 3, dim(DATA)[2]/3)
MED <- apply(DATA, 1:2, function(x) median(x, na.rm = TRUE))
rownames(MED) <- c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3", "b", "sauc", "S/N/p", "conv")
# MED

load("LN1/N20/HR1_p0.4.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med4  <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv4 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)
pro  <- matrix(DATA[12,], ncol = 3, byrow = TRUE)
pro4 <- sapply(1:3, function(i) mean(pro[,i], na.rm = TRUE))
dim(DATA) <- c(13, 3, dim(DATA)[2]/3)
MED <- apply(DATA, 1:2, function(x) median(x, na.rm = TRUE))
rownames(MED) <- c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3", "b", "sauc", "S/N/p", "conv")
# MED

load("LN1/N20/HR1_p0.2.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med2  <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv2 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)
pro  <- matrix(DATA[12,], ncol = 3, byrow = TRUE)
pro2 <- sapply(1:3, function(i) mean(pro[,i], na.rm = TRUE))
dim(DATA) <- c(13, 3, dim(DATA)[2]/3)
MED <- apply(DATA, 1:2, function(x) median(x, na.rm = TRUE))
rownames(MED) <- c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3", "b", "sauc", "S/N/p", "conv")
# MED

x5 <- rbind(med8, med6, med4, med2)

```

### LN1-2

```{r, fig.width = 10, fig.height = 5}


load("LN1/N20/HR2_p0.8.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med8 <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv8 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)
pro  <- matrix(DATA[12,], ncol = 3, byrow = TRUE)
pro8 <- sapply(1:3, function(i) mean(pro[,i], na.rm = TRUE))
dim(DATA) <- c(13, 3, dim(DATA)[2]/3)
MED <- apply(DATA, 1:2, function(x) median(x, na.rm = TRUE))
rownames(MED) <- c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3", "b", "sauc", "S/N/p", "conv")
# MED

load("LN1/N20/HR2_p0.6.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med6  <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv6 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)
pro  <- matrix(DATA[12,], ncol = 3, byrow = TRUE)
pro6 <- sapply(1:3, function(i) mean(pro[,i], na.rm = TRUE))
dim(DATA) <- c(13, 3, dim(DATA)[2]/3)
MED <- apply(DATA, 1:2, function(x) median(x, na.rm = TRUE))
rownames(MED) <- c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3", "b", "sauc", "S/N/p", "conv")
# MED

load("LN1/N20/HR2_p0.4.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med4  <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv4 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)
pro  <- matrix(DATA[12,], ncol = 3, byrow = TRUE)
pro4 <- sapply(1:3, function(i) mean(pro[,i], na.rm = TRUE))
dim(DATA) <- c(13, 3, dim(DATA)[2]/3)
MED <- apply(DATA, 1:2, function(x) median(x, na.rm = TRUE))
rownames(MED) <- c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3", "b", "sauc", "S/N/p", "conv")
# MED

load("LN1/N20/HR2_p0.2.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med2  <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv2 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)
pro  <- matrix(DATA[12,], ncol = 3, byrow = TRUE)
pro2 <- sapply(1:3, function(i) mean(pro[,i], na.rm = TRUE))
dim(DATA) <- c(13, 3, dim(DATA)[2]/3)
MED <- apply(DATA, 1:2, function(x) median(x, na.rm = TRUE))
rownames(MED) <- c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3", "b", "sauc", "S/N/p", "conv")
# MED

x6 <- rbind(med8, med6, med4, med2)

```

### U13-1

```{r, fig.width = 10, fig.height = 5}


load("U13/N20/HR1_p0.8.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med8 <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv8 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)
pro  <- matrix(DATA[12,], ncol = 3, byrow = TRUE)
pro8 <- sapply(1:3, function(i) mean(pro[,i], na.rm = TRUE))
dim(DATA) <- c(13, 3, dim(DATA)[2]/3)
MED <- apply(DATA, 1:2, function(x) median(x, na.rm = TRUE))
rownames(MED) <- c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3", "b", "sauc", "S/N/p", "conv")
# MED

load("U13/N20/HR1_p0.6.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med6  <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv6 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)
pro  <- matrix(DATA[12,], ncol = 3, byrow = TRUE)
pro6 <- sapply(1:3, function(i) mean(pro[,i], na.rm = TRUE))
dim(DATA) <- c(13, 3, dim(DATA)[2]/3)
MED <- apply(DATA, 1:2, function(x) median(x, na.rm = TRUE))
rownames(MED) <- c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3", "b", "sauc", "S/N/p", "conv")
# MED

load("U13/N20/HR1_p0.4.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med4  <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv4 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)
pro  <- matrix(DATA[12,], ncol = 3, byrow = TRUE)
pro4 <- sapply(1:3, function(i) mean(pro[,i], na.rm = TRUE))
dim(DATA) <- c(13, 3, dim(DATA)[2]/3)
MED <- apply(DATA, 1:2, function(x) median(x, na.rm = TRUE))
rownames(MED) <- c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3", "b", "sauc", "S/N/p", "conv")
# MED

load("U13/N20/HR1_p0.2.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med2  <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv2 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)
pro  <- matrix(DATA[12,], ncol = 3, byrow = TRUE)
pro2 <- sapply(1:3, function(i) mean(pro[,i], na.rm = TRUE))
dim(DATA) <- c(13, 3, dim(DATA)[2]/3)
MED <- apply(DATA, 1:2, function(x) median(x, na.rm = TRUE))
rownames(MED) <- c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3", "b", "sauc", "S/N/p", "conv")
# MED

x7 <- rbind(med8, med6, med4, med2)

```

### U13-2

```{r, fig.width = 10, fig.height = 5}
load("U13/N20/HR2_p0.8.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med8 <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv8 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)
pro  <- matrix(DATA[12,], ncol = 3, byrow = TRUE)
pro8 <- sapply(1:3, function(i) mean(pro[,i], na.rm = TRUE))
dim(DATA) <- c(13, 3, dim(DATA)[2]/3)
MED <- apply(DATA, 1:2, function(x) median(x, na.rm = TRUE))
rownames(MED) <- c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3", "b", "sauc", "S/N/p", "conv")
# MED

load("U13/N20/HR2_p0.6.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med6  <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv6 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)
pro  <- matrix(DATA[12,], ncol = 3, byrow = TRUE)
pro6 <- sapply(1:3, function(i) median(pro[,i], na.rm = TRUE))
dim(DATA) <- c(13, 3, dim(DATA)[2]/3)
MED <- apply(DATA, 1:2, function(x) median(x, na.rm = TRUE))
rownames(MED) <- c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3", "b", "sauc", "S/N/p", "conv")
# MED

load("U13/N20/HR2_p0.4.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med4  <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv4 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)
pro  <- matrix(DATA[12,], ncol = 3, byrow = TRUE)
pro4 <- sapply(1:3, function(i) mean(pro[,i], na.rm = TRUE))
dim(DATA) <- c(13, 3, dim(DATA)[2]/3)
MED <- apply(DATA, 1:2, function(x) median(x, na.rm = TRUE))
rownames(MED) <- c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3", "b", "sauc", "S/N/p", "conv")
# MED

load("U13/N20/HR2_p0.2.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med2  <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv2 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)
pro  <- matrix(DATA[12,], ncol = 3, byrow = TRUE)
pro2 <- sapply(1:3, function(i) mean(pro[,i], na.rm = TRUE))
dim(DATA) <- c(13, 3, dim(DATA)[2]/3)
MED <- apply(DATA, 1:2, function(x) median(x, na.rm = TRUE))
rownames(MED) <- c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3", "b", "sauc", "S/N/p", "conv")
# MED

x8 <- rbind(med8, med6, med4, med2)
```


```{r, fig.width = 10, fig.height = 5}

par(mfcol = c(2, 4), oma = c(0.2, 4, 0.2, 0.3), mar = c(3, 0.2, 2, 0.2))


matplot(x1, ylim = c(0.7, 0.9), type = "o", ylab = "Med(SAUC)", xlab = "p", xaxt = "n", pch = 1:3)
legend("topleft", c("All studies", "Published studies", "Sensitivity analysis"), col = 1:3, lty = 1:3, pch = 1:3)
axis(1, at = 1:4, labels = seq(0.8, 0.2, -0.2))
title("EX(0.2)")

matplot(x2, ylim = c(0.5, 0.7), type = "o", ylab = "Med(SAUC)", xlab = "p", xaxt = "n", pch = 1:3)
axis(1, at = 1:4, labels = seq(0.8, 0.2, -0.2))

matplot(x3, ylim = c(0.7, 0.9), type = "o", ylab = "Med(SAUC)", xlab = "p", xaxt = "n", yaxt = "n", pch = 1:3)
axis(1, at = 1:4, labels = seq(0.8, 0.2, -0.2))
title("EX(0.5)")

matplot(x4, ylim = c(0.5, 0.7), type = "o", ylab = "Med(SAUC)", xlab = "p", xaxt = "n", yaxt = "n", pch = 1:3)
axis(1, at = 1:4, labels = seq(0.8, 0.2, -0.2))

matplot(x5, ylim = c(0.7, 0.9), type = "o", ylab = "Med(SAUC)", xlab = "p", xaxt = "n",  yaxt = "n", pch = 1:3)
axis(1, at = 1:4, labels = seq(0.8, 0.2, -0.2))
title("LN1")

matplot(x6, ylim = c(0.5, 0.7), type = "o", ylab = "Med(SAUC)", xlab = "p", xaxt = "n", yaxt = "n", pch = 1:3)
axis(1, at = 1:4, labels = seq(0.8, 0.2, -0.2))

matplot(x7, ylim = c(0.7, 0.9), type = "o", ylab = "Med(SAUC)", xlab = "p", xaxt = "n", yaxt = "n", pch = 1:3)
axis(1, at = 1:4, labels = seq(0.8, 0.2, -0.2))
title("U(1,3)")


matplot(x8, ylim = c(0.5, 0.7), type = "o", ylab = "Med(SAUC)", xlab = "p", xaxt = "n", yaxt = "n", pch = 1:3)
axis(1, at = 1:4, labels = seq(0.8, 0.2, -0.2))



```
