---
title: "Simulation Result 2"
author: "Yi"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.width = 12, fig.height = 5)
options(knitr.kable.NA = '')
library(knitr)
library(kableExtra)
```

Notation: 

- $T$: time-to-event

- $X^{(s)}_i$: the biomarker measure of $i$th person in the $s$th study


### 1 Samll HR


Simulation scenario 1

- If $T ≤ 2$, $X^{(s)}_i\sim 0.7 + 0.1e_i^{(s)}$

- If $T > 2$, $X^{(s)}_i\sim 0.3 + 0.3e_i^{(s)}$

- $e_i^{(s)} \sim logistic(n^{(s)})$



```{r, include=FALSE}
load("a-calc/beta_1_alpha_20.RData")
# set$set1
# p <- seq(0.8, 0.2, -0.2)

# N=20 -------------------------------------------------------------------------

load("N20/HR1_p0.8.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med8 <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv   <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv8  <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)
pro  <- matrix(DATA[12,], ncol = 3, byrow = TRUE)
pro8 <- sapply(1:3, function(i) mean(pro[,i], na.rm = TRUE))
dim(DATA) <- c(13, 3, dim(DATA)[2]/3)
MED <- apply(DATA, 1:2, function(x) median(x, na.rm = TRUE))
rownames(MED) <- c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3", "b", "sauc", "S/N/p", "conv")
# MED

load("N20/HR1_p0.6.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med6  <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv6 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)
pro  <- matrix(DATA[12,], ncol = 3, byrow = TRUE)
pro6 <- sapply(1:3, function(i) mean(pro[,i], na.rm = TRUE))
dim(DATA) <- c(13, 3, dim(DATA)[2]/3)
MED <- apply(DATA, 1:2, function(x) median(x, na.rm = TRUE))
rownames(MED) <- c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3", "b", "sauc", "S/N/p", "conv")
# MED

load("N20/HR1_p0.4.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med4  <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv4 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)
pro  <- matrix(DATA[12,], ncol = 3, byrow = TRUE)
pro4 <- sapply(1:3, function(i) mean(pro[,i], na.rm = TRUE))
dim(DATA) <- c(13, 3, dim(DATA)[2]/3)
MED <- apply(DATA, 1:2, function(x) median(x, na.rm = TRUE))
rownames(MED) <- c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3", "b", "sauc", "S/N/p", "conv")
# MED

load("N20/HR1_p0.2.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med2  <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv2 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)
pro  <- matrix(DATA[12,], ncol = 3, byrow = TRUE)
pro2 <- sapply(1:3, function(i) mean(pro[,i], na.rm = TRUE))
dim(DATA) <- c(13, 3, dim(DATA)[2]/3)
MED <- apply(DATA, 1:2, function(x) median(x, na.rm = TRUE))
rownames(MED) <- c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3", "b", "sauc", "S/N/p", "conv")
# MED

x1 <- rbind(med8, med6, med4, med2)

cr1 <- rbind(cv8, cv6, cv4, cv2)


# N=30 -------------------------------------------------------------------------

load("N30/HR1_p0.8.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med8 <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv   <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv8  <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)
pro  <- matrix(DATA[12,], ncol = 3, byrow = TRUE)
pro8 <- sapply(1:3, function(i) mean(pro[,i], na.rm = TRUE))
dim(DATA) <- c(13, 3, dim(DATA)[2]/3)
MED <- apply(DATA, 1:2, function(x) median(x, na.rm = TRUE))
rownames(MED) <- c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3", "b", "sauc", "S/N/p", "conv")
# MED

load("N30/HR1_p0.6.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med6  <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv6 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)
pro  <- matrix(DATA[12,], ncol = 3, byrow = TRUE)
pro6 <- sapply(1:3, function(i) mean(pro[,i], na.rm = TRUE))
dim(DATA) <- c(13, 3, dim(DATA)[2]/3)
MED <- apply(DATA, 1:2, function(x) median(x, na.rm = TRUE))
rownames(MED) <- c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3", "b", "sauc", "S/N/p", "conv")
# MED

load("N30/HR1_p0.4.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med4  <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv4 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)
pro  <- matrix(DATA[12,], ncol = 3, byrow = TRUE)
pro4 <- sapply(1:3, function(i) mean(pro[,i], na.rm = TRUE))
dim(DATA) <- c(13, 3, dim(DATA)[2]/3)
MED <- apply(DATA, 1:2, function(x) median(x, na.rm = TRUE))
rownames(MED) <- c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3", "b", "sauc", "S/N/p", "conv")
# MED

load("N30/HR1_p0.2.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med2  <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv2 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)
pro  <- matrix(DATA[12,], ncol = 3, byrow = TRUE)
pro2 <- sapply(1:3, function(i) mean(pro[,i], na.rm = TRUE))
dim(DATA) <- c(13, 3, dim(DATA)[2]/3)
MED <- apply(DATA, 1:2, function(x) median(x, na.rm = TRUE))
rownames(MED) <- c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3", "b", "sauc", "S/N/p", "conv")
# MED

x2 <- rbind(med8, med6, med4, med2)

cr2 <- rbind(cv8, cv6, cv4, cv2)


# N=50 -------------------------------------------------------------------------

load("N50/HR1_p0.8.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med8 <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv   <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv8  <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)
pro  <- matrix(DATA[12,], ncol = 3, byrow = TRUE)
pro8 <- sapply(1:3, function(i) mean(pro[,i], na.rm = TRUE))
dim(DATA) <- c(13, 3, dim(DATA)[2]/3)
MED <- apply(DATA, 1:2, function(x) median(x, na.rm = TRUE))
rownames(MED) <- c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3", "b", "sauc", "S/N/p", "conv")
# MED

load("N50/HR1_p0.6.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med6  <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv6 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)
pro  <- matrix(DATA[12,], ncol = 3, byrow = TRUE)
pro6 <- sapply(1:3, function(i) mean(pro[,i], na.rm = TRUE))
dim(DATA) <- c(13, 3, dim(DATA)[2]/3)
MED <- apply(DATA, 1:2, function(x) median(x, na.rm = TRUE))
rownames(MED) <- c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3", "b", "sauc", "S/N/p", "conv")
# MED

load("N50/HR1_p0.4.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med4  <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv4 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)
pro  <- matrix(DATA[12,], ncol = 3, byrow = TRUE)
pro4 <- sapply(1:3, function(i) mean(pro[,i], na.rm = TRUE))
dim(DATA) <- c(13, 3, dim(DATA)[2]/3)
MED <- apply(DATA, 1:2, function(x) median(x, na.rm = TRUE))
rownames(MED) <- c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3", "b", "sauc", "S/N/p", "conv")
# MED

load("N50/HR1_p0.2.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med2  <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv2 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)
pro  <- matrix(DATA[12,], ncol = 3, byrow = TRUE)
pro2 <- sapply(1:3, function(i) mean(pro[,i], na.rm = TRUE))
dim(DATA) <- c(13, 3, dim(DATA)[2]/3)
MED <- apply(DATA, 1:2, function(x) median(x, na.rm = TRUE))
rownames(MED) <- c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3", "b", "sauc", "S/N/p", "conv")
# MED

x3 <- rbind(med8, med6, med4, med2)

cr3 <- rbind(cv8, cv6, cv4, cv2)
```


```{r}
par(mfrow=c(1,3))

matplot(x1, ylim = c(0.7, 0.9), type = "o", ylab = "Med(SAUC)", xlab = "p", xaxt = "n", pch = 1:3)
legend("topleft", c("All studies", "Published studies", "Sensitivity analysis"), col = 1:3, lty = 1:3, pch = 1:3)
axis(1, at = 1:4, labels = seq(0.8, 0.2, -0.2))
title("N=20")

matplot(x2, ylim = c(0.7, 0.9), type = "o", ylab = "Med(SAUC)", xlab = "p", xaxt = "n", pch = 1:3)
legend("topleft", c("All studies", "Published studies", "Sensitivity analysis"), col = 1:3, lty = 1:3, pch = 1:3)
axis(1, at = 1:4, labels = seq(0.8, 0.2, -0.2))
title("N=30")

matplot(x3, ylim = c(0.7, 0.9), type = "o", ylab = "Med(SAUC)", xlab = "p", xaxt = "n", pch = 1:3)
legend("topleft", c("All studies", "Published studies", "Sensitivity analysis"), col = 1:3, lty = 1:3, pch = 1:3)
axis(1, at = 1:4, labels = seq(0.8, 0.2, -0.2))
title("N=50")

par(mfrow=c(1,1))

cr <- cbind(cr1, cr2, cr3)
rownames(cr) <- paste0("p = ", seq(0.8, 0.2, -0.2))
cr %>%
  kbl(caption ="Convergence rate, EXP(0.2)") %>%
  kable_classic_2(full_width = F)%>%
  add_header_above(c(" "=1, rep(c("All \n studies" = 1, "Published \n studies" = 1, "Sensitivity \n analysis" = 1),3))) %>%
  add_header_above(c(" "=1, "N = 20" = 3, "N = 30" = 3, "N = 50" = 3))



```

### 2 Moderate HR

Simulation scenario

- If $T ≤ 2$, $X^{(s)}_i\sim 0.7 + 0.1e_i^{(s)}$

- If $T > 2$, $X^{(s)}_i\sim 0.1 + 0.5e_i^{(s)}$

- $e_i^{(s)} \sim logistic(n^{(s)})$



```{r}
load("a-calc/beta_1_alpha_20.RData")
# N=20 -------------------------------------------------------------------------

load("N20/HR2_p0.8.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med8 <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv   <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv8  <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)
pro  <- matrix(DATA[12,], ncol = 3, byrow = TRUE)
pro8 <- sapply(1:3, function(i) mean(pro[,i], na.rm = TRUE))
dim(DATA) <- c(13, 3, dim(DATA)[2]/3)
MED <- apply(DATA, 1:2, function(x) median(x, na.rm = TRUE))
rownames(MED) <- c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3", "b", "sauc", "S/N/p", "conv")
# MED

load("N20/HR2_p0.6.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med6  <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv6 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)
pro  <- matrix(DATA[12,], ncol = 3, byrow = TRUE)
pro6 <- sapply(1:3, function(i) mean(pro[,i], na.rm = TRUE))
dim(DATA) <- c(13, 3, dim(DATA)[2]/3)
MED <- apply(DATA, 1:2, function(x) median(x, na.rm = TRUE))
rownames(MED) <- c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3", "b", "sauc", "S/N/p", "conv")
# MED

load("N20/HR2_p0.4.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med4  <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv4 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)
pro  <- matrix(DATA[12,], ncol = 3, byrow = TRUE)
pro4 <- sapply(1:3, function(i) mean(pro[,i], na.rm = TRUE))
dim(DATA) <- c(13, 3, dim(DATA)[2]/3)
MED <- apply(DATA, 1:2, function(x) median(x, na.rm = TRUE))
rownames(MED) <- c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3", "b", "sauc", "S/N/p", "conv")
# MED

load("N20/HR2_p0.2.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med2  <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv2 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)
pro  <- matrix(DATA[12,], ncol = 3, byrow = TRUE)
pro2 <- sapply(1:3, function(i) mean(pro[,i], na.rm = TRUE))
dim(DATA) <- c(13, 3, dim(DATA)[2]/3)
MED <- apply(DATA, 1:2, function(x) median(x, na.rm = TRUE))
rownames(MED) <- c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3", "b", "sauc", "S/N/p", "conv")
# MED

x1 <- rbind(med8, med6, med4, med2)

cr1 <- rbind(cv8, cv6, cv4, cv2)


# N=30 -------------------------------------------------------------------------

load("N30/HR2_p0.8.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med8 <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv   <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv8  <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)
pro  <- matrix(DATA[12,], ncol = 3, byrow = TRUE)
pro8 <- sapply(1:3, function(i) mean(pro[,i], na.rm = TRUE))
dim(DATA) <- c(13, 3, dim(DATA)[2]/3)
MED <- apply(DATA, 1:2, function(x) median(x, na.rm = TRUE))
rownames(MED) <- c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3", "b", "sauc", "S/N/p", "conv")
# MED

load("N30/HR2_p0.6.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med6  <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv6 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)
pro  <- matrix(DATA[12,], ncol = 3, byrow = TRUE)
pro6 <- sapply(1:3, function(i) mean(pro[,i], na.rm = TRUE))
dim(DATA) <- c(13, 3, dim(DATA)[2]/3)
MED <- apply(DATA, 1:2, function(x) median(x, na.rm = TRUE))
rownames(MED) <- c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3", "b", "sauc", "S/N/p", "conv")
# MED

load("N30/HR2_p0.4.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med4  <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv4 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)
pro  <- matrix(DATA[12,], ncol = 3, byrow = TRUE)
pro4 <- sapply(1:3, function(i) mean(pro[,i], na.rm = TRUE))
dim(DATA) <- c(13, 3, dim(DATA)[2]/3)
MED <- apply(DATA, 1:2, function(x) median(x, na.rm = TRUE))
rownames(MED) <- c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3", "b", "sauc", "S/N/p", "conv")
# MED

load("N30/HR2_p0.2.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med2  <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv2 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)
pro  <- matrix(DATA[12,], ncol = 3, byrow = TRUE)
pro2 <- sapply(1:3, function(i) mean(pro[,i], na.rm = TRUE))
dim(DATA) <- c(13, 3, dim(DATA)[2]/3)
MED <- apply(DATA, 1:2, function(x) median(x, na.rm = TRUE))
rownames(MED) <- c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3", "b", "sauc", "S/N/p", "conv")
# MED

x2 <- rbind(med8, med6, med4, med2)

cr2 <- rbind(cv8, cv6, cv4, cv2)


# N=50 -------------------------------------------------------------------------

load("N50/HR2_p0.8.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med8 <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv   <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv8  <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)
pro  <- matrix(DATA[12,], ncol = 3, byrow = TRUE)
pro8 <- sapply(1:3, function(i) mean(pro[,i], na.rm = TRUE))
dim(DATA) <- c(13, 3, dim(DATA)[2]/3)
MED <- apply(DATA, 1:2, function(x) median(x, na.rm = TRUE))
rownames(MED) <- c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3", "b", "sauc", "S/N/p", "conv")
# MED

load("N50/HR2_p0.6.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med6  <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv6 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)
pro  <- matrix(DATA[12,], ncol = 3, byrow = TRUE)
pro6 <- sapply(1:3, function(i) mean(pro[,i], na.rm = TRUE))
dim(DATA) <- c(13, 3, dim(DATA)[2]/3)
MED <- apply(DATA, 1:2, function(x) median(x, na.rm = TRUE))
rownames(MED) <- c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3", "b", "sauc", "S/N/p", "conv")
# MED

load("N50/HR2_p0.4.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med4  <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv4 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)
pro  <- matrix(DATA[12,], ncol = 3, byrow = TRUE)
pro4 <- sapply(1:3, function(i) mean(pro[,i], na.rm = TRUE))
dim(DATA) <- c(13, 3, dim(DATA)[2]/3)
MED <- apply(DATA, 1:2, function(x) median(x, na.rm = TRUE))
rownames(MED) <- c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3", "b", "sauc", "S/N/p", "conv")
# MED

load("N50/HR2_p0.2.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med2  <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv2 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)
pro  <- matrix(DATA[12,], ncol = 3, byrow = TRUE)
pro2 <- sapply(1:3, function(i) mean(pro[,i], na.rm = TRUE))
dim(DATA) <- c(13, 3, dim(DATA)[2]/3)
MED <- apply(DATA, 1:2, function(x) median(x, na.rm = TRUE))
rownames(MED) <- c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3", "b", "sauc", "S/N/p", "conv")
# MED

x3 <- rbind(med8, med6, med4, med2)

cr3 <- rbind(cv8, cv6, cv4, cv2)

```



```{r}
par(mfrow=c(1,3))

matplot(x1, ylim = c(0.5, 0.8), type = "o", ylab = "Med(SAUC)", xlab = "p", xaxt = "n", pch = 1:3)
legend("topleft", c("All studies", "Published studies", "Sensitivity analysis"), col = 1:3, lty = 1:3, pch = 1:3)
axis(1, at = 1:4, labels = seq(0.8, 0.2, -0.2))
title("N=20")

matplot(x2, ylim = c(0.5, 0.8), type = "o", ylab = "Med(SAUC)", xlab = "p", xaxt = "n", pch = 1:3)
legend("topleft", c("All studies", "Published studies", "Sensitivity analysis"), col = 1:3, lty = 1:3, pch = 1:3)
axis(1, at = 1:4, labels = seq(0.8, 0.2, -0.2))
title("N=30")

matplot(x3, ylim = c(0.5, 0.8), type = "o", ylab = "Med(SAUC)", xlab = "p", xaxt = "n", pch = 1:3)
legend("topleft", c("All studies", "Published studies", "Sensitivity analysis"), col = 1:3, lty = 1:3, pch = 1:3)
axis(1, at = 1:4, labels = seq(0.8, 0.2, -0.2))
title("N=50")

par(mfrow=c(1,1))

cr <- cbind(cr1, cr2, cr3)
rownames(cr) <- paste0("p = ", seq(0.8, 0.2, -0.2))
cr %>%
  kbl(caption ="Convergence rate, EXP(0.2)") %>%
  kable_classic_2(full_width = F)%>%
  add_header_above(c(" "=1, rep(c("All \n studies" = 1, "Published \n studies" = 1, "Sensitivity \n analysis" = 1),3))) %>%
  add_header_above(c(" "=1, "N = 20" = 3, "N = 30" = 3, "N = 50" = 3))



```
