---
title: "Ki67 Example"
author: "Yi"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
rm(list = ls())
files.sources <- list.files(path = "../funs/")
x <- sapply(paste0("../funs/", files.sources), source)
library(mixmeta)
library(readxl)
library(pryr)
```



```{r, include=FALSE}
##
## LOAD DATA
##

## MEDIAN FU 
med.data <- read_excel("Ki67.xlsx", sheet = "MCT")
med.data$mty <- med.data$mct_mo/12

## OBTAIN ETA
eta <- cens.eta(data = med.data, med.year = mty,  n1 = n1, n0 = n0, s1_med = s1_mct, s0_med = s0_mct)$par


## OS DATA

os.data  <- read_excel("Ki67.xlsx", sheet = "OS")
os.data$ty <- os.data$t/12

## HR DATA

dataHR <-read_excel("Ki67.xlsx", sheet = "HR")
dataHR$u_lnHR <- log(dataHR$HR)
ln_ci.low   <- log(dataHR$ci.low)
ln_ci.up    <- log(dataHR$ci.up)
se          <- (ln_ci.up - ln_ci.low)/(2 * qnorm(0.975))
dataHR$v_lnHR <- se^2

## MERGED DATA (OS+HR)
os_hr <- merge(os.data, dataHR, all.x = TRUE)

## THE NUMBER OF UNIQUE DATA
length(unique(os_hr$study))
```



```{r, include=FALSE}
## 5-YEAR DATA

data.05 <- convert.dt(
  data = os_hr, tK = 5, study = study, ty = ty, 
  n1 = n1, n0 = n0, s1 = s1, s0 = s0, u_lnHR = u_lnHR, v_lnHR = v_lnHR, 
  eta = eta)

## REMOVE OBSERVATIONS WITH MISSING VALUES
data.5 <- data.05[complete.cases(data.05),]

## 3-YEAR DATA

data.03 <- convert.dt(
  data = os_hr, tK = 3, study = study, ty = ty, 
  n1 = n1, n0 = n0, s1 = s1, s0 = s0, u_lnHR = u_lnHR, v_lnHR = v_lnHR, 
  eta = eta)

## REMOVE OBSERVATIONS WITH MISSING VALUES
data.3 <- data.03[complete.cases(data.03),]
```



```{r, include=FALSE}
## DATA

data <- data.3
# data <- data.5


{
  y1  <- data$u_sen
  y2  <- data$u_spe 
  y3  <- data$u_lnHR
  
  v1  <- data$v_sen
  v2  <- data$v_spe 
  v3  <- data$v_lnHR
  
  v12 <- data$v_senspe 
  v13 <- data$v_senlnHR 
  v23 <- data$v_spelnHR
}


```


# Time-dependent SROC 

## Reitsma Model


```{r}

bnm.int    <- c(mean(y1), mean(y2), mean(v1), mean(v2), mean(v12))
fn.bnm.ml  <- function(par) .llk.BNM.ml(par, y1, y2, v1, v2, v12)
opt.bnm.ml <- nlminb(bnm.int, fn.bnm.ml)
par.bnm.ml <- opt.bnm.ml$par
hes.bnm    <- numDeriv::hessian(fn.bnm.ml, opt.bnm.ml$par)
rownames(hes.bnm) <- colnames(hes.bnm) <- c("mu.se", "mu.sp", "tau.sp", "tau.sp", "rho")

sauc.bnm <- SAUC.ci(par.bnm.ml, var.matrix = solve(hes.bnm), sauc.type = "sroc" )

# sauc.bnm
```


## Sensitivity analysis

```{r, fig.height=5, fig.width=5, include=FALSE}

## TNM MODEL (CHELESKEY DECOMPOSITION)

y <- as.matrix( cbind(y1, y2, y3) )
S <- as.matrix( cbind(v1, v12, v13, v2, v23, v3) )
fit.tnm <- mixmeta(y, S, method = "ml")


u0    <- fit.tnm$coefficients
tau   <- c(fit.tnm$Psi)
t1230 <- sqrt(tau[c(1, 5, 9)])
r10   <- prod(tau[2]/prod(sqrt(tau[c(1, 5)])))
r30   <- prod(tau[3]/prod(sqrt(tau[c(1, 9)])))
r20   <- prod(tau[6]/prod(sqrt(tau[c(5, 9)])))


par3 <- c(u0, t1230, r10, r20, r30)
names(par3) <- c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3")
par3
sauc3 <- SAUC(par3[c(1,2,4,5,7)])


## INITIAL VALUE

init3 <- c(mean(y1), mean(y2), mean(y3), mean(v1), mean(v2), mean(v3), mean(v12), mean(v13), mean(v23))
# fn.tnm.cho <- function(par) .llk.TNM.cho(par, y1, y2, y3, v1, v2, v3, v12, v13, v23)
# fn.tnmcho <- nlminb(par3, fn.tnm.cho)
# round(fn.tnmcho$par, 6)

fn.tnm.ml <- function(par) .llk.TNM.ml(par, y1, y2, y3, v1, v2, v3, v12, v13, v23)
fn.tnmml<- nlminb(par3, fn.tnm.ml)
fn.tnmml$par

PAR.O <- sapply(seq(1, 0.1, -0.1), function(p){
  
  fn.o <- function(par) .clk.TNM.ml(par, y1, y2, y3, v1, v2, v3, v12, v13, v23,
                            p = p, 
                            a.interval= c(-10, 10)
                            )

opt.o <- nlminb(c(par3, 1), fn.o)
              # # method = "L-BFGS-B",
              # lower = c(rep(-Inf,3), rep(0,3),   rep(-1,3), 0),
              # upper = c(rep( Inf,3), rep(Inf,3), rep( 1,3), 5)
              # )

# sauc <- SAUC(par = opt.o$par[c(1,2,4,5,7)])

par <- c(opt.o$convergence, opt.o$par, plogis(opt.o$par[1:2]))
names(par) <- c("conv", 
                "mu.se", "mu.sp", "mu.lnhr", "tau.se", "tau.sp", "tau.lnhr", "rho1", "rho2", "rho3",
                "beta",
                "sen", "spe")
par
})


colnames(PAR.O) <- seq(1, 0.1, -0.1)
round(PAR.O,4)

```


### 3-YEAR SAUC (CI)


```{r, fig.height=5, fig.width=5}

sauc.sa <- sapply(seq(1, 0.1, -0.1), function(p){
  
  fn.o <- function(par) .clk.TNM.ml(par, y1, y2, y3, v1, v2, v3, v12, v13, v23,
                            p = p, 
                            a.interval= c(-10, 10)
                            )

  opt.o <- nlminb(c(par3, 1), fn.o)
              # # method = "L-BFGS-B",
              # lower = c(rep(-Inf,3), rep(-Inf,3), rep(-1,3), 0),
              # upper = c(rep( Inf,3), rep(Inf,3), rep( 1,3), 2)
              # )

num.hessian <- numDeriv::hessian(fn.o, opt.o$par)
rownames(num.hessian) <- colnames(num.hessian) <- c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3", "b")

if (p==1) inv.I.fun.m <- solve(num.hessian[-10,-10]) else inv.I.fun.m <- solve(num.hessian)

var.matrix <-  inv.I.fun.m[c(1,2,4,5,7), c(1,2,4,5,7)]

sauc.ci <- SAUC.ci(opt.o$par[c(1,2,4,5,7)],
                   var.matrix = var.matrix, sauc.type = "sroc")

c(sauc = sauc.ci, conv = opt.o$convergence)

})

sauc.mat.3 <- cbind(c(sauc.bnm, conv = fn.tnmml$convergence), sauc.sa[,-1])
sauc.mat.3

# matplot(y = t(sauc.mat.3[1:3,]), ylim = c(0.5,0.8), type = "b", 
#         pch = 20, col = c(1,2,2), lty = c(1, 2,2), xlab = "p", ylab = "SAUC",  xaxt = "n")
# axis(1, at = 1:10, labels = seq(1,0.1,-0.1))
# title(main = paste0(3, " year"))


```




### 3-YEAR SA given 23/38

```{r, fig.height=5, fig.width=5}


fn.o <- function(par) .clk.TNM.ml(par, y1, y2, y3, v1, v2, v3, v12, v13, v23,
                         p = 0.6, 
                         a.interval= c(-10, 10)
                         )


opt.o <- nlminb(c(init3,1), fn.o)
           # method = "L-BFGS-B",
           # lower = c(rep(-Inf,3), rep(-Inf,3), rep(-1,3), 0),
           # upper = c(rep( Inf,3), rep(Inf,3), rep( 1,3), 2)
           # )

num.hessian <- numDeriv::hessian(fn.o, opt.o$par)
rownames(num.hessian) <- colnames(num.hessian) <- c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3", "b")
var.ml <- solve(num.hessian)
var.matrix <-  var.ml[c(1,2,4,5,7), c(1,2,4,5,7)]

sauc.ci <- SAUC.ci(opt.o$par[c(1,2,4,5,7)], var.matrix = var.matrix, sauc.type = "sroc")

par <- c(opt.o$par,  sauc.ci, plogis(opt.o$par[1:2]), opt.o$convergence)
names(par) <- c( "u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3",
             "b",
             "sauc", "sauc.lb", "sauc.ub",
             "sen", "spe", "conv")
par
par.mvm.3 <- cbind(par.bnm.ml, par[c(1,2,4,5,7)])
par.mvm.3

## p = 1, 0.6, 0.2

# par.mvm.3 <- cbind(par.bnm.ml, par[c(1,2,4,5,7)])
# SROC(par = par.mvm.3, sroc.type = "sroc")
# points(plogis(-y2), plogis(y1))
# title("3 year with p = 23/38")

```



```{r, include=FALSE}
## DATA

data <- data.5
# data <- data.5


{
  y1  <- data$u_sen
  y2  <- data$u_spe 
  y3  <- data$u_lnHR
  
  v1  <- data$v_sen
  v2  <- data$v_spe 
  v3  <- data$v_lnHR
  
  v12 <- data$v_senspe 
  v13 <- data$v_senlnHR 
  v23 <- data$v_spelnHR
}


```


# Time-dependent SROC 

## Reitsma Model


```{r}

bnm.int    <- c(mean(y1), mean(y2), mean(v1), mean(v2), mean(v12))
fn.bnm.ml  <- function(par) .llk.BNM.ml(par, y1, y2, v1, v2, v12)
opt.bnm.ml <- nlminb(bnm.int, fn.bnm.ml)
par.bnm.ml <- opt.bnm.ml$par
hes.bnm    <- numDeriv::hessian(fn.bnm.ml, opt.bnm.ml$par)
rownames(hes.bnm) <- colnames(hes.bnm) <- c("mu.se", "mu.sp", "tau.sp", "tau.sp", "rho")

sauc.bnm <- SAUC.ci(par.bnm.ml, var.matrix = solve(hes.bnm), sauc.type = "sroc" )

# sauc.bnm
```


## Sensitivity analysis

```{r, fig.height=5, fig.width=5, include=FALSE}

## TNM MODEL (CHELESKEY DECOMPOSITION)

y <- as.matrix( cbind(y1, y2, y3) )
S <- as.matrix( cbind(v1, v12, v13, v2, v23, v3) )
fit.tnm <- mixmeta(y, S, method = "ml")


u0    <- fit.tnm$coefficients
tau   <- c(fit.tnm$Psi)
t1230 <- sqrt(tau[c(1, 5, 9)])
r10   <- prod(tau[2]/prod(sqrt(tau[c(1, 5)])))
r30   <- prod(tau[3]/prod(sqrt(tau[c(1, 9)])))
r20   <- prod(tau[6]/prod(sqrt(tau[c(5, 9)])))


par3 <- c(u0, t1230, r10, r20, r30)
names(par3) <- c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3")
par3
sauc3 <- SAUC(par3[c(1,2,4,5,7)])


## INITIAL VALUE

init3 <- c(mean(y1), mean(y2), mean(y3), mean(v1), mean(v2), mean(v3), mean(v12), mean(v13), mean(v23))
# fn.tnm.cho <- function(par) .llk.TNM.cho(par, y1, y2, y3, v1, v2, v3, v12, v13, v23)
# fn.tnmcho <- nlminb(par3, fn.tnm.cho)
# round(fn.tnmcho$par, 6)

fn.tnm.ml <- function(par) .llk.TNM.ml(par, y1, y2, y3, v1, v2, v3, v12, v13, v23)
fn.tnmml<- nlminb(par3, fn.tnm.ml)
fn.tnmml$par

PAR.O <- sapply(seq(1, 0.1, -0.1), function(p){
  
  fn.o <- function(par) .clk.TNM.ml(par, y1, y2, y3, v1, v2, v3, v12, v13, v23,
                            p = p, 
                            a.interval= c(-10, 10)
                            )

opt.o <- nlminb(c(par3, 1), fn.o)
              # # method = "L-BFGS-B",
              # lower = c(rep(-Inf,3), rep(0,3),   rep(-1,3), 0),
              # upper = c(rep( Inf,3), rep(Inf,3), rep( 1,3), 5)
              # )

# sauc <- SAUC(par = opt.o$par[c(1,2,4,5,7)])

par <- c(opt.o$convergence, opt.o$par, plogis(opt.o$par[1:2]))
names(par) <- c("conv", 
                "mu.se", "mu.sp", "mu.lnhr", "tau.se", "tau.sp", "tau.lnhr", "rho1", "rho2", "rho3",
                "beta",
                "sen", "spe")
par
})


colnames(PAR.O) <- seq(1, 0.1, -0.1)
round(PAR.O,4)

```


### 5-YEAR SAUC (CI)


```{r, fig.height=5, fig.width=5}
sauc.sa <- sapply(seq(1, 0.1, -0.1), function(p){
  
  fn.o <- function(par) .clk.TNM.ml(par, y1, y2, y3, v1, v2, v3, v12, v13, v23,
                            p = p, 
                            a.interval= c(-10, 10)
                            )

  opt.o <- nlminb(c(par3, 1), fn.o)
              # # method = "L-BFGS-B",
              # lower = c(rep(-Inf,3), rep(-Inf,3), rep(-1,3), 0),
              # upper = c(rep( Inf,3), rep(Inf,3), rep( 1,3), 2)
              # )

num.hessian <- numDeriv::hessian(fn.o, opt.o$par)
rownames(num.hessian) <- colnames(num.hessian) <- c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3", "b")

if (p==1) inv.I.fun.m <- solve(num.hessian[-10,-10]) else inv.I.fun.m <- solve(num.hessian)

var.matrix <-  inv.I.fun.m[c(1,2,4,5,7), c(1,2,4,5,7)]

sauc.ci <- SAUC.ci(opt.o$par[c(1,2,4,5,7)],
                   var.matrix = var.matrix, sauc.type = "sroc")

c(sauc = sauc.ci, conv = opt.o$convergence)

})

sauc.mat.5 <- cbind(c(sauc.bnm, conv = fn.tnmml$convergence), sauc.sa[,-1])
sauc.mat.5
```

#### PLOT1

```{r, fig.height=5, fig.width=10}
par(mfrow = c(1,2))

matplot(y = t(sauc.mat.3[1:3,]), ylim = c(0.5,0.8), type = "b", 
        pch = 20, col = c(1,2,2), lty = c(1, 2,2), xlab = "p", ylab = "SAUC",  xaxt = "n")
axis(1, at = 1:10, labels = seq(1,0.1,-0.1))
title(main = paste0(3, " year"))

matplot(y = t(sauc.mat.5[1:3,]), ylim = c(0.5,0.8), type = "b", 
        pch = 20, col = c(1,2,2), lty = c(1, 2,2), xlab = "p", ylab = "SAUC",  xaxt = "n")
axis(1, at = 1:10, labels = seq(1,0.1,-0.1))
title(main = paste0(5, " year"))

par(mfrow = c(1,1))
```




### 5-YEART SA given 23/38

```{r, fig.height=5, fig.width=5}
fn.o <- function(par) .clk.TNM.ml(par, y1, y2, y3, v1, v2, v3, v12, v13, v23,
                         p = 0.6, 
                         a.interval= c(-10, 10)
                         )


opt.o <- nlminb(c(init3,1), fn.o)
           # method = "L-BFGS-B",
           # lower = c(rep(-Inf,3), rep(-Inf,3), rep(-1,3), 0),
           # upper = c(rep( Inf,3), rep(Inf,3), rep( 1,3), 2)
           # )

num.hessian <- numDeriv::hessian(fn.o, opt.o$par)
rownames(num.hessian) <- colnames(num.hessian) <- c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3", "b")
var.ml <- solve(num.hessian)
var.matrix <-  var.ml[c(1,2,4,5,7), c(1,2,4,5,7)]

sauc.ci <- SAUC.ci(opt.o$par[c(1,2,4,5,7)], var.matrix = var.matrix, sauc.type = "sroc")

par <- c(opt.o$par,  sauc.ci, plogis(opt.o$par[1:2]), opt.o$convergence)
names(par) <- c( "u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3",
             "b",
             "sauc", "sauc.lb", "sauc.ub",
             "sen", "spe", "conv")
# par
par.mvm.5 <- cbind(par.bnm.ml, par[c(1,2,4,5,7)])
par.mvm.5

```

#### PLOT2

```{r, fig.height=5, fig.width=10}
## p = 1, 0.6, 0.2
par(mfrow = c(1,2))

SROC(par = par.mvm.3, sroc.type = "sroc")
points(plogis(-y2), plogis(y1))
legend("bottomright", 
       bty='n',
       legend = c(sprintf("p = %.1f, SAUC = %.3f", c(1, 23/38), c(sauc.mat.3[1,c(1,5)]))), 
       col = c("black", "grey"), pch = 18, pt.cex = 2, cex = 1, 
       lty = rep(1,2))
title("3 year")

SROC(par = par.mvm.5, sroc.type = "sroc")
points(plogis(-y2), plogis(y1))
legend("bottomright", 
       bty='n',
       legend = c(sprintf("p = %.1f, SAUC = %.3f", c(1, 23/38), c(sauc.mat.5[1,c(1,5)]))), 
       col = c("black", "grey"), pch = 18, pt.cex = 2, cex = 1, 
       lty = rep(1,2))
title("5 year")

par(mfrow = c(1,1))

```








