---
title: "Ki67 Example"
author: "Yi"
output:
  pdf_document: default
  html_document: default
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
rm(list = ls())
```


```{r, include=FALSE}
files.sources <- list.files(path = "../R/")
x <- sapply(paste0("../R/", files.sources), source)
library(readxl)
library(knitr)
library(kableExtra)
library(latex2exp)
library(numDeriv)

saveplot <- FALSE

```


```{r, include=FALSE}
##
## LOAD DATA
##

## MEDIAN FU 
med.data <- read_excel("Ki67.xlsx", sheet = "MCT")
med.data$mty <- med.data$mct_mo/12

## OBTAIN ETA
eta <- cens.eta(data = med.data, med.year = mty,  n1 = n1, n0 = n0, s1_med = s1_mct, s0_med = s0_mct)$par


## OS DATA

os.data  <- read_excel("Ki67.xlsx", sheet = "OS")
os.data$ty <- os.data$t/12

## HR DATA

dataHR <-read_excel("Ki67.xlsx", sheet = "HR")
dataHR$u_lnHR <- log(dataHR$HR)
ln_ci.low   <- log(dataHR$ci.low)
ln_ci.up    <- log(dataHR$ci.up)
se          <- (ln_ci.up - ln_ci.low)/(2 * qnorm(0.975))
dataHR$v_lnHR <- se^2

## MERGED DATA (OS+HR)
os_hr <- merge(os.data, dataHR, all.x = TRUE)


## LOG-HR DATA
dataHRALL <-read_excel("Ki67.xlsx", sheet = "HR_all")
dataHRALL$u_lnHR <- log(dataHRALL$HR)
ln_ci.low   <- log(dataHRALL$ci.low)
ln_ci.up    <- log(dataHRALL$ci.up)
se          <- (ln_ci.up - ln_ci.low)/(2 * qnorm(0.975))
dataHRALL$v_lnHR <- se^2
dataHRALL$t_lnHR <- dataHRALL$u_lnHR/se

studylab.hr <- dataHRALL$author
studylab.d1 <- unname(unlist(dataHRALL[dataHRALL$D==1, "author"]))
studylab.t3 <- studylab.hr %in% unname(unlist(os.data[os.data$ty==3, "author"])) 
studylab.t5 <- studylab.hr %in% unname(unlist(os.data[os.data$ty==5, "author"]))

t1 <- dataHRALL[dataHRALL$D==1,]$t_lnHR
t0 <- dataHRALL[dataHRALL$D==0,]$t_lnHR
t1.t3 <- dataHRALL[studylab.t3,]$t_lnHR
t0.t3 <- dataHRALL[!studylab.t3,]$t_lnHR
t1.t5 <- dataHRALL[studylab.t5,]$t_lnHR
t0.t5 <- dataHRALL[!studylab.t5,]$t_lnHR

## THE NUMBER OF UNIQUE DATA
# length(unique(os_hr$study))
```


# Funnel plot

```{r, fig.width=12, fig.height=4}
library(metafor)
library(meta)

# sort((dataHRALL$cutoff))

# dt <- na.omit(dataHRALL[dataHRALL$cutoff==0.1,])
# mt <- metagen(dt$u_lnHR, sqrt(dt$v_lnHR), sm = "MD", method.tau = "PM")
# metabias(mt, plotit = TRUE, method.bias = "Egger")
# funnel(mt)

if (saveplot) {setEPS(width = 12, height = 4); postscript("ki67-tf.eps")}

par(mfrow = c(1,3))
res <- rma(yi=u_lnHR, vi=v_lnHR, data=na.omit(dataHRALL[dataHRALL$cutoff==0.1,]), slab=author)
res.tf <- trimfill(res)
funnel(res.tf, cex=1.2, xlim=c(-2,3), legend = FALSE)
title("Cutoff = 10%")
title("(A)", adj = 0, font.main = 1, cex.main = 1)


res <- rma(yi=u_lnHR, vi=v_lnHR, data=na.omit(dataHRALL[dataHRALL$cutoff>0.1 & dataHRALL$cutoff<=0.2,]), slab=author)
res.tf <- trimfill(res)
funnel(res.tf, cex=1.2, xlim=c(-2,3), legend = FALSE)
title("10% < Cutoff <= 20")
title("(B)", adj = 0, font.main = 1, cex.main = 1)


plot(t1, rep(1,   length(t1.t3)), pch="|", col=1, cex = 1, ylim = c(0,1), xlim = c(-3,7),
					xlab = "t-statistic", ylab = "Probability of publication", yaxt='n')
axis(2, at=c(0,1), labels = c("Unpublished", "Published"))
points(t0, rep(0.95,   length(t0.t3)), pch="|", col="darkgrey", cex = 1)
legend("bottomleft", 
       bty='n',
       legend = c("Published and reported KM estimates", "Published but no KM estimates"), 
       col = c("black", "darkgrey"), cex = 1, 
       lty = rep(1,2))
title("(C)", adj = 0, font.main = 1, cex.main = 1)
title("The t-statistic of 38 published studies")


if(saveplot) dev.off()

par(mfrow = c(1,1))

```


```{r, include=FALSE}


output.result <- function(TK=5){
	
	data <- convert.dt(
	data = os_hr, tK = TK, study = study, ty = ty, 
	n1 = n1, n0 = n0, s1 = s1, s0 = s0, u_lnHR = u_lnHR, v_lnHR = v_lnHR, 
	eta = eta)

## REMOVE OBSERVATIONS WITH MISSING VALUES
data <- na.omit(data)

## OBS DATA

{
  y1  <- data$u_sen
  y2  <- data$u_spe 
  y3  <- data$u_lnHR
  
  v1  <- data$v_sen
  v2  <- data$v_spe 
  v3  <- data$v_lnHR
  
  v12 <- data$v_senspe 
  v13 <- data$v_senlnHR 
  v23 <- data$v_spelnHR
}

## BNM Model of Hattori and Zhou

bnm.int <- rep(0.1, 5)
fn.bnm.ml  <- function(par) llk.BNM.ml(par, y1, y2, v1, v2, v12)
opt.bnm.ml <- nlminb(bnm.int, fn.bnm.ml)

par.bnm.ml <- opt.bnm.ml$par
hes.bnm    <- numDeriv::hessian(fn.bnm.ml, opt.bnm.ml$par)
rownames(hes.bnm) <- colnames(hes.bnm) <- c("mu.se", "mu.sp", "tau.sp", "tau.sp", "rho")
sauc.bnm   <- SAUC.ci(par.bnm.ml, var.matrix = solve(hes.bnm), sauc.type = "sroc" )


## Sensitivity analysis


PAR.tnm <- sapply(seq(0.9, 0.1, -0.1), function(p){
  
  progmeta.sa(
  y1, y2, y3, v1, v2, v3, v12, v13, v23, 
    p = p, 
    sauc.type = "sroc",
    a.interval= c(-10, 10))
  
})
PAR.bnm <- c(par.bnm.ml[1:2], NA, par.bnm.ml[3:4], NA, par.bnm.ml[5], rep(NA, 4), 
													sauc.bnm, NA, NA, opt.bnm.ml$convergence)

PAR.all <- cbind(PAR.bnm, PAR.tnm)
colnames(PAR.all) <- c("HZ", paste0("p=", seq(0.9, 0.1, -0.1)))
rownames(PAR.all) <- c(paste0("mu",1:3), paste0("tau",1:3), paste0("rho",1:3), "beta", "alpha",
																			"sauc", "sauc.lb", "sauc.ub", "sen", "spe", "converge")

# round(PAR, 3) %>%
#   kbl(caption ="Parameters from TNM") %>%
#   kable_classic_2(full_width = F)


## SAUC-CI

## OUTPUT1: SAUC
par.sauc <- PAR.all[c(12:14),]

# round(sauc.mat,3) %>%
#   kbl(caption ="SAUC") %>%
#   kable_classic_2(full_width = F)

## OUTPUT2: PAR
par.sroc <- PAR.all[c(1,2,4,5,7), c(1, 4,6,8)]  ##p = 0.7, 0.5, 0.3

## OUTPUT3: ALPHA, BETA
par.ab <- PAR.all[c(10,11),c(4,6,8)] 

res <- list(data = data, 
												par.all = PAR.all, par.sroc= par.sroc, par.sauc = par.sauc, par.ab=par.ab)

return(res)

}


res3 <- output.result(TK=3)
res5 <- output.result(TK=5)


```




```{r table1}
sroc.tab <- function(res = res3, 
																					cap ="Estimates of the parameters for the SROC curve at $t=3$",
																					lab = "sroc-ki67-3"){
	

TB1 <- t(round(res$par.all, 3)[c(1:11),c(1,4,6,8)])
TB1.c1 <- sprintf("%.3f (%.3f)", TB1[,1], plogis(TB1[,1]))
TB1.c2 <- sprintf("%.3f (%.3f)", TB1[,2], plogis(TB1[,2]))
TB1.c3 <- sprintf("%.3f (%.3f)", TB1[,3], exp(TB1[,3]))
TB1.fn <- cbind(TB1.c1, TB1.c2, TB1.c3, TB1[,-c(1:3)])
TB1.fn[1,3] <- NA
header <- c("",
		"$\\mu_\\mathrm{sen}$ (sen)", "$\\mu_\\mathrm{spe}$ (sen)","$\\mu_\\mathrm{lnHR}$ (HR)",
		"$\\psi_\\mathrm{sen}$", "$\\psi_\\mathrm{spe}$", "$\\psi_\\mathrm{lnHR}$",
		"$\\rho_1$", "$\\rho_2$", "$\\rho_3$", "$\\beta$", "$\\alpha$")
col0 <- c("HZ", "Prop ($p=0.7$)", "Prop ($p=0.5$)", "Prop ($p=0.3$)")
TB1.fn <- cbind(col0, TB1.fn)
rownames(TB1.fn) <- NULL
colnames(TB1.fn) <- header

output <- TB1.fn %>%
  kbl(
    caption = cap,
    # format = ifelse(save.tex, "latex", "html"),
    format = "latex",
    longtable = F, 
    booktabs = T,
    align = "r",
    position = "!htb",
    linesep = "",
    escape = FALSE,
    label = lab) %>%
  footnote(general = "
			$\\rho_1$ denotes the correlation coefficient between $\\mu_\\mathrm{sen}$ and $\\mu_\\mathrm{spe}$;
			$\\rho_2$ denotes that between $\\mu_\\mathrm{sen}$ and $\\mu_\\mathrm{lnHR}$;
			$\\rho_1$ denotes that between $\\mu_\\mathrm{spe}$ and $\\mu_\\mathrm{lnHR}$.", 
   escape = FALSE, 
			threeparttable = TRUE,  
			general_title = "") 

return(output)
}

sink("SROC-ki67-3.tex")
sroc.tab(res = res3, cap ="Estimates of the parameters for the SROC curve at $t=3$", lab = "sroc-ki67-3")
sink()

sink("SROC-ki67-5.tex")
sroc.tab(res = res5, cap ="Estimates of the parameters for the SROC curve at $t=5$", lab = "sroc-ki67-5")
sink()

```


```{r table2}

TB3 <- t(round(res3$par.all, 3)[12:14,])
sauc3 <- sprintf("%.3f (%.3f, %.3f)", TB3[,1], TB3[,2], TB3[,3])
col0 <- c("SAUC (95\\% CI)")

TB5 <- t(round(res5$par.all, 3)[12:14,])
sauc5 <- sprintf("%.3f (%.3f, %.3f)", TB5[,1], TB5[,2], TB5[,3])
col0 <- c("SAUC (95\\% CI)")

col <- c("HZ", "$p=0.9", "$p=0.8", "$p=0.7", "$p=0.6", "$p=0.5",
									"$p=0.4", "$p=0.3", "$p=0.2", "$p=0.1")
TB <- cbind(col, sauc3, sauc5)

rownames(TB) <- NULL
colnames(TB) <- c("","SAUC(3) (95\\% CI)", "SAUC(5) (95\\% CI)")

sink("SAUC-ki67.tex")

TB %>%
  kbl(
    caption="The estimated SAUC with 95\\% condifence intervals at $t=3$ and $t=5$",
    format ="latex",
    # format = ifelse(save.tex, "latex", "html"),
    # format = "latex",
    longtable = F, 
    booktabs = T,
    align = "r",
    position = "!htb",
    linesep = "",
    # linesep = c(rep('',3), '\\addlinespace'),
    escape = FALSE,
    label = "sauc-ki67") 
# %>%  add_header_above(c("","HZ", paste0("p =", seq(0.9, 0.1, -0.1))),escape = FALSE) 

sink()


```





```{r SAUC, fig.height=8, fig.width=12}
saveplot <- FALSE
if (saveplot) {setEPS(width = 12, height = 8); postscript("ki67.eps")}
title.cex <- 1.2

par(mfcol= c(2,3))

## SROC
SROC(par = res3$par.sroc, sroc.type = "sroc", spoint.cex = 2, col = gray.colors(4, gamma = 1, start = 0, end = 0.8))
points(plogis(-res3$data$u_spe), plogis(res3$data$u_sen))
legend("bottomright", 
       bty='n',
       legend = c(sprintf("HZ, SAUC = %.3f", res3$par.sauc[1,1]), 
       											sprintf("p = %.2f, SAUC = %.3f", c(0.7, 0.5, 0.3), c(res3$par.sauc[1,c(4,6,8)]))), 
       col = gray.colors(4, gamma = 1, start = 0, end = 0.8), 
       pch = 18, pt.cex = 1.5, cex = 1.5, 
       lty = rep(1,2))
title("t = 3 (year)")
title("(A)", adj = 0, font.main = 1, cex.main = title.cex)


SROC(par = res5$par.sroc, sroc.type = "sroc", spoint.cex = 2)
points(plogis(-res5$data$u_spe), plogis(res5$data$u_sen))
legend("bottomright", 
       bty='n',
       legend = c(sprintf("HZ, SAUC = %.3f", res5$par.sauc[1,1]), 
       											sprintf("p = %.2f, SAUC = %.3f", c(0.7, 0.5, 0.3), c(res5$par.sauc[1,c(4,6,8)]))), 
       col = gray.colors(4, gamma = 1, start = 0, end = 0.8), 
       pch = 18, pt.cex = 1.5, cex = 1.5, 
       lty = rep(1,2))
title("t = 5 (year)")
title("(D)", adj = 0, font.main = 1, cex.main = title.cex)


## SAUC
matplot(y = t(res3$par.sauc), ylim = c(0.5,0.8), type = "b", 
        pch = 20, col = c("black","darkgrey","darkgrey"), 
								lty = c(1, 2,2), xlab = "p", ylab = "SAUC",  xaxt = "n")
axis(1, at = 1:10, labels = seq(1,0.1,-0.1))
title("t = 3 (year)")
legend("bottomleft", 
       bty='n',
       legend = c("SAUC", "95% CI"), 
       col = c("black", "darkgrey"),
       lty = c(1,2),
							cex = 1.5)
title("(B)", adj = 0, font.main = 1, cex.main = title.cex)

matplot(y = t(res3$par.sauc), ylim = c(0.5,0.8), type = "b", 
        pch = 20, col = c("black","darkgrey","darkgrey"), 
								lty = c(1, 2,2), xlab = "p", ylab = "SAUC",  xaxt = "n")
axis(1, at = 1:10, labels = seq(1,0.1,-0.1))
title("t = 5 (year)")
legend("bottomleft", 
       bty='n',
       legend = c("SAUC", "95% CI"), 
       col = c("black", "darkgrey"), 
       lty = c(1,2),
							cex = 1.5)
title("(E)", adj = 0, font.main = 1, cex.main = title.cex)



## A
beta1  <- res3$par.ab[1,1]
alpha1 <- res3$par.ab[2,1]
beta2  <- res3$par.ab[1,2]
alpha2 <- res3$par.ab[2,2]
beta3  <- res3$par.ab[1,3]
alpha3 <- res3$par.ab[2,3]

curve(pnorm(beta1*x + alpha1), -10, 15, ylim = c(0,1), xlim = c(-3,7),
      xlab = "", ylab = "",
      col=1,
      yaxt='n')
curve(pnorm(beta2*x + alpha2), -5, 10, add = TRUE, col=2) 
curve(pnorm(beta3*x + alpha3), -5, 10, add = TRUE, col=3)
axis(2, at=c(0,0.5,1), labels = c(0,0.5,1))
points(t1.t3, rep(1,   length(t1.t3)), pch="|", col=1, cex = 1)
points(t0.t3, rep(0.95,   length(t0.t3)), pch="|", col="darkgrey", cex = 1)
title("t = 3 (year)")
legend("bottomright", 
       bty='n',
       legend = TeX(sprintf("$p = %.1f$", c(0.7,0.5,0.3))), 
       col = 1:3, cex = 1.5, 
       lty = rep(1,3))
title("(C)", adj = 0, font.main = 1, cex.main = title.cex)
mtext(TeX("$p = \\Phi(\\beta \\, t + \\alpha)$"), side=2, line=2, at=c(0.5), cex = 1)
title(xlab = "t", line=2, cex = 0.7)


## B
beta1  <- res5$par.ab[1,1]
alpha1 <- res5$par.ab[2,1]
beta2  <- res5$par.ab[1,2]
alpha2 <- res5$par.ab[2,2]
beta3  <- res5$par.ab[1,3]
alpha3 <- res5$par.ab[2,3]

curve(pnorm(beta1*x + alpha1), -5, 10, ylim = c(0,1), xlim = c(-3,7),
      xlab = "", ylab="",
      col=1,
      yaxt='n')
curve(pnorm(beta2*x + alpha2), -5, 10, add = TRUE, col=2) 
curve(pnorm(beta3*x + alpha3), -5, 10, add = TRUE, col=3)
axis(2, at=c(0,0.5,1), labels = c(0,0.5,1))
points(t1.t5, rep(1, length(t1.t5)), pch="|", col=1, cex = 1)
points(t0.t5, rep(0.95, length(t0.t5)), pch="|", col="darkgrey", cex = 1)
# abline(h=0.5, col = "grey", lty=2)
title("t = 5 (year)")
legend("bottomright", 
       bty='n',
       legend = TeX(sprintf("$p = %.1f$", c(0.7,0.5,0.3))), 
       col = 1:3, cex = 1.5, 
       lty = rep(1,3))
title("(F)", adj = 0, font.main = 1, cex.main = title.cex)
mtext(TeX("$p = \\Phi(\\beta \\, t + \\alpha)$"), side=2, line=2, at=c(0.5), cex = 1)
title(xlab = "t", line=2, cex = 0.7)
# abline(h=0.5, col = "grey", lty=2)


par(mfrow = c(1,1))

if(saveplot) dev.off()
```



