---
title: "BoxPlot-b1-N50"
author: "Yi"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.width = 5, fig.height = 5)
options(knitr.kable.NA = '')
library(knitr)
library(kableExtra)
```



## Median

Number of patients $\sim Uniform[30, 50], b = 1$

Others follows Hattori (2016).

```{r, fig.width = 10, fig.height = 5}

p <- seq(0.9, 0.1, -0.2)

load("resb1/DATA_N50_HR1_p0.9.RData")
sauc <- matrix(DATA[11,], ncol = 8, byrow = TRUE)
med9  <- sapply(1:8, function(i) median(sauc[,i], na.rm = TRUE))
load("resb1/DATA_N50_HR1_p0.7.RData")
sauc <- matrix(DATA[11,], ncol = 8, byrow = TRUE)
med7  <- sapply(1:8, function(i) median(sauc[,i], na.rm = TRUE))
load("resb1/DATA_N50_HR1_p0.5.RData")
sauc <- matrix(DATA[11,], ncol = 8, byrow = TRUE)
med5  <- sapply(1:8, function(i) median(sauc[,i], na.rm = TRUE))
load("resb1/DATA_N50_HR1_p0.3.RData")
sauc <- matrix(DATA[11,], ncol = 8, byrow = TRUE)
med3  <- sapply(1:8, function(i) median(sauc[,i], na.rm = TRUE))
load("resb1/DATA_N50_HR1_p0.1.RData")
sauc <- matrix(DATA[11,], ncol = 8, byrow = TRUE)
med1  <- sapply(1:8, function(i) median(sauc[,i], na.rm = TRUE))
	
# x <- rbind(med9, med7, med5, med3, med1)
# matplot(x, ylim = c(0.7, 1), type = "o", ylab = "Med(SAUC)", xlab = "p", xaxt = "n", pch = 1:8)
# legend("bottomleft", c("bnm.p", "tnm.p", "tnm.p2", "bnm.o","tnm.o","tnm.o2",  "sa1", "sa2"), col = 1:8, lty = 1:8, pch = 1:8)
# title("Compared with BNM model")
# axis(1, at = 1:5, labels = seq(0.9, 0.1, -0.2))

x <- rbind(med9, med7, med5, med3, med1)
matplot(x[,c(1,4,7,8)], ylim = c(0.7, 1), type = "o", ylab = "Med(SAUC)", xlab = "p", xaxt = "n", pch = 1:4)
legend("topleft", c("bnm.All", "bnm.Published", "SA.1", "SA.2"), col = 1:4, lty = 1:4, pch = 1:4)

axis(1, at = 1:5, labels = seq(0.9, 0.1, -0.2))

```





## Boxplot of SAUC

```{r, fig.width = 8, fig.height = 5, echo=FALSE}
load("resb1/DATA_N50_HR1_p0.9.RData")
source("res.R")

kbl(x, caption = "p = 0.9")%>%
  kable_classic(full_width = F, html_font = "Cambria", position = "center")

load("resb1/DATA_N50_HR1_p0.7.RData")
source("res.R")

kbl(x, caption = "p = 0.7")%>%
  kable_classic(full_width = F, html_font = "Cambria", position = "center")

load("resb1/DATA_N50_HR1_p0.5.RData")
source("res.R")

kbl(x, caption = "p = 0.5")%>%
  kable_classic(full_width = F, html_font = "Cambria", position = "center")

load("resb1/DATA_N50_HR1_p0.3.RData")
source("res.R")

kbl(x, caption = "p = 0.3")%>%
  kable_classic(full_width = F, html_font = "Cambria", position = "center")

load("resb1/DATA_N50_HR1_p0.1.RData")
source("res.R")

kbl(x, caption = "p = 0.1")%>%
  kable_classic(full_width = F, html_font = "Cambria", position = "center")
```



<!-- ## All Med S1 -->

<!-- ```{r, fig.width = 10, fig.height = 5} -->

<!-- p <- seq(0.9, 0.1, -0.2) -->

<!-- load("resb1/DATA_N50_HR2_p0.9.RData") -->
<!-- sauc <- matrix(DATA[11,], ncol = 8, byrow = TRUE) -->
<!-- med9  <- sapply(1:8, function(i) mean(sauc[,i], na.rm = TRUE)) -->
<!-- load("resb1/DATA_N50_HR2_p0.7.RData") -->
<!-- sauc <- matrix(DATA[11,], ncol = 8, byrow = TRUE) -->
<!-- med7  <- sapply(1:8, function(i) mean(sauc[,i], na.rm = TRUE)) -->
<!-- load("resb1/DATA_N50_HR2_p0.5.RData") -->
<!-- sauc <- matrix(DATA[11,], ncol = 8, byrow = TRUE) -->
<!-- med5  <- sapply(1:8, function(i) mean(sauc[,i], na.rm = TRUE)) -->
<!-- load("resb1/DATA_N50_HR2_p0.3.RData") -->
<!-- sauc <- matrix(DATA[11,], ncol = 8, byrow = TRUE) -->
<!-- med3  <- sapply(1:8, function(i) mean(sauc[,i], na.rm = TRUE)) -->
<!-- load("resb1/DATA_N50_HR2_p0.1.RData") -->
<!-- sauc <- matrix(DATA[11,], ncol = 8, byrow = TRUE) -->
<!-- med1  <- sapply(1:8, function(i) mean(sauc[,i], na.rm = TRUE)) -->

<!-- x <- rbind(med9, med7, med5, med3, med1) -->
<!-- matplot(x, ylim = c(0.5, 0.7), type = "o", ylab = "Med(SAUC)", xlab = "p", xaxt = "n", pch = 1:8) -->
<!-- legend("bottomleft", c("bnm.p", "tnm.p", "tnm.p2", "bnm.o","tnm.o","tnm.o2",  "sa1", "sa2"), col = 1:8, lty = 1:8, pch = 1:8) -->
<!-- title("Compared with BNM model") -->
<!-- axis(1, at = 1:5, labels = seq(0.9, 0.1, -0.2)) -->

<!-- ``` -->





<!-- ## S1 -->

<!-- ```{r, fig.width = 10, fig.height = 5, echo=FALSE} -->
<!-- load("resb1/DATA_N50_HR2_p0.9.RData") -->
<!-- source("res.R") -->

<!-- kbl(x)%>% -->
<!--   kable_classic(full_width = F, html_font = "Cambria", position = "center") -->

<!-- load("resb1/DATA_N50_HR2_p0.7.RData") -->
<!-- source("res.R") -->

<!-- kbl(x)%>% -->
<!--   kable_classic(full_width = F, html_font = "Cambria", position = "center") -->

<!-- load("resb1/DATA_N50_HR2_p0.5.RData") -->
<!-- source("res.R") -->

<!-- kbl(x)%>% -->
<!--   kable_classic(full_width = F, html_font = "Cambria", position = "center") -->

<!-- load("resb1/DATA_N50_HR2_p0.3.RData") -->
<!-- source("res.R") -->

<!-- kbl(x)%>% -->
<!--   kable_classic(full_width = F, html_font = "Cambria", position = "center") -->

<!-- load("resb1/DATA_N50_HR2_p0.1.RData") -->
<!-- source("res.R") -->

<!-- kbl(x)%>% -->
<!--   kable_classic(full_width = F, html_font = "Cambria", position = "center") -->
<!-- ``` -->

