---
title: "The counter plot of alpha and beta in the eelection function"
subtitle: "Exp(0.2)"
author: "Yi"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
options(knitr.kable.NA = '')
rm(list = ls())

library(survival)
library(testit)
## LOAD FUNCTIONS

files.sources <- list.files(path = "../../R/")
x <- sapply(paste0("../../R/", files.sources), source)
```


```{r, fig.width=6, fig.height=6}

ab.counter.plot <- function(path, mk.id, title){
  # load("a-calc/beta1_pts50_150.RData")
  
  load(path)
  if (mk.id == 1) mk <- set$mk1 else if (mk.id == 2) mk <- set$mk2 else mk <- set$mk3
  
  p_dataSt.all <- population.data.list(1000, 2, N.min = set$pts.dist[1], N.max = set$pts.dist[1],
                                  CD="EXP", Exp.r = 0.2, 
                                  x1.u = mk[1], x2.u = mk[2], 
                                  x1.s = mk[3], x2.s = mk[4], 
                                  v.sd = mk[5])
  p_dataSt <- as.data.frame(t(sapply(1:length(p_dataSt.all), function(i) p_dataSt.all[[i]][[1]])))
  p_dataSt <- p_dataSt[complete.cases(p_dataSt),]
      
  eta <- cens.eta(data = p_dataSt, med.year = med.ty, n1 = n1, n0 = n0, s1_med = s1_mct, s0_med = s0_mct)$par
  dataSt.p <- convert.dt(data = p_dataSt, tK=2, study = study.id, ty = ty, n1 = n1, n0 = n0, s1 = s1, s0 = s0, u_lnHR = u_lnHR, v_lnHR = v_lnHR, eta = eta)
      
  dataSt.p <- dataSt.p[complete.cases(dataSt.p),]
  
  b <- seq(0,5,0.5)
  atb <- seq(min(b), max(b), 0.5)
  a <- seq(-7, 7, 0.5)
  ata <- seq(min(a), max(a), 0.5)
  ba <- expand.grid(b=b, a=a)
  n <- nrow(ba)
  lb <- length(b)
  la <- length(a)
  
  p.a.e <- vapply(1:n, function(j){
    
    t <- dataSt.p$t_lnHR
    mean <- mean(pnorm(ba$a[j]+ba$b[j]*t, lower.tail = TRUE))
    med <- median(pnorm(ba$a[j]+ba$b[j]*t, lower.tail = TRUE))
    c(mean, med)
  }, c(mean=0, med=0))
  
  colnames(p.a.e) <- paste0(ba$b, ";", ba$a)
  
  bap <- matrix(p.a.e[1,], lb, la, dimnames = list(b, a))
  bap2 <- matrix(p.a.e[2,], lb, la, dimnames = list(b, a))
  
  
  z <- round(t(bap),2)
    
  contour(a, b, z, axes = FALSE, frame.plot = FALSE)
  axis(1, at=ata)
  axis(2, at=atb)
  title(title)
  grid()
}
```


```{r, fig.width=12, fig.height=4}
par(mfrow = c(1, 3))
ab.counter.plot("a-calc/beta1_pts50_150.RData", mk.id = 1, "U(50,150); Biomarker1")
ab.counter.plot("a-calc/beta1_pts50_150.RData", mk.id = 2, "U(50,150); Biomarker2")
ab.counter.plot("a-calc/beta1_pts50_150.RData", mk.id = 3, "U(50,150); Biomarker3")
par(mfrow = c(1, 3))
```


```{r, fig.width=12, fig.height=4}
par(mfrow = c(1, 3))
ab.counter.plot("a-calc/beta1_pts50_300.RData", mk.id = 1, "U(50,300); Biomarker1")
ab.counter.plot("a-calc/beta1_pts50_300.RData", mk.id = 2, "U(50,300); Biomarker2")
ab.counter.plot("a-calc/beta1_pts50_300.RData", mk.id = 3, "U(50,150); Biomarker3")
par(mfrow = c(1, 3))
```
