---
title: "The SROC(2) curves and funnel plot on the lnHR"
subtitle: "Exp(0.2)"
author: "Yi"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
options(knitr.kable.NA = '')
rm(list = ls())

library(survival)
library(testit)
library(metafor)
## LOAD FUNCTIONS

files.sources <- list.files(path = "../../R/")
x <- sapply(paste0("../../R/", files.sources), source)
```


```{r, include=FALSE}


SROC.tstat <- function(path, S, mk.id, a){
# load("a-calc/beta1_pts50_300.RData")
# mk <- set$mk2


  load(path)
  if (mk.id == 1) mk <- set$mk1 else mk <- set$mk2
  
  p_dataSt.all <- population.data.list(S, 2, N.min = set$pts.dist[1], N.max = set$pts.dist[1],
                                  CD="EXP", Exp.r = 0.2, 
                                  x1.u = mk[1], x2.u = mk[2], 
                                  x1.s = mk[3], x2.s = mk[4], 
                                  v.sd = mk[5])
  p_dataSt <- as.data.frame(t(sapply(1:length(p_dataSt.all), function(i) p_dataSt.all[[i]][[1]])))
  p_dataSt <- p_dataSt[complete.cases(p_dataSt),]
      
  eta <- cens.eta(data = p_dataSt, med.year = med.ty, n1 = n1, n0 = n0, s1_med = s1_mct, s0_med = s0_mct)$par
  dataSt.p <- convert.dt(data = p_dataSt, tK=2, study = study.id, ty = ty, n1 = n1, n0 = n0, s1 = s1, s0 = s0, u_lnHR = u_lnHR, v_lnHR = v_lnHR, eta = eta)
      
  dataSt.p <- dataSt.p[complete.cases(dataSt.p),]
  
  dataST.p.sort <- dataSt.p[order(dataSt.p$t_lnHR, decreasing = TRUE ),]
  dataST.p.sort$sort.id <- 1:nrow(dataST.p.sort)
  
  
  b <- 1

  select.p  <- pnorm(b * abs(dataSt.p$t_lnHR) + a)
  dataSt.p$select.p  <- select.p
  dataSt.p$select.id <- rbinom(nrow(dataSt.p), 1, select.p) 
  
  dataSt.o <- dataSt.p[dataSt.p$select.id == 1, ]
  p.e <- mean(pnorm(b * dataSt.p$t_lnHR + a), na.rm = TRUE)

  ## POPULATION DATA
    
    p.y1  <- dataSt.p$u_sen
    p.y2  <- dataSt.p$u_spe 
    p.y3  <- dataSt.p$u_lnHR

    p.s11  <- dataSt.p$v_sen
    p.s22  <- dataSt.p$v_spe 
    p.s33  <- dataSt.p$v_lnHR
    
    p.s12 <- dataSt.p$v_senspe 
    p.s13 <- dataSt.p$v_senlnHR 
    p.s23 <- dataSt.p$v_spelnHR 
    t.p   <- dataSt.p$t_lnHR

    ## OBSERVED DATA
    
    o.y1  <- dataSt.o$u_sen
    o.y2  <- dataSt.o$u_spe 
    o.y3  <- dataSt.o$u_lnHR
    
    o.s11  <- dataSt.o$v_sen
    o.s22  <- dataSt.o$v_spe 
    o.s33  <- dataSt.o$v_lnHR
    
    o.s12 <- dataSt.o$v_senspe 
    o.s13 <- dataSt.o$v_senlnHR 
    o.s23 <- dataSt.o$v_spelnHR 
      
  
  
    tnm.int <- c(rep(0,3), rep(0.1, 3), rep(-0.1, 3))
    bnm.int <- c(rep(0,2), rep(0.1, 2), -0.1)
    b0 <- 0.5
    
    
    ## FIRST PLOT
    
    par(mfrow = c(1,2))
    
    p.sen <- plogis(p.y1)
    p.fpr <- plogis(-p.y2)
    plot(p.fpr, p.sen, col = "grey", cex = dataSt.p$t_lnHR/2, xlim = c(0,1), ylim = c(0,1),
         xlab = "1-Specificity", ylab = "Sensitivity")

    o.sen <- plogis(o.y1)
    o.fpr <- plogis(-o.y2)
    points(o.fpr, o.sen, col = "black", cex = dataSt.o$t_lnHR/2)
    legend("bottomright", c("Published", "Unpublished"), col = c("black", "grey"), pch = c(1,1))
    title(sprintf("Proportion of published = %.2f", p.e))
    
    
    ## 1 BNM.P ----
    {
      
      fn.bnm.ml  <- function(par) llk.BNM.ml(par, p.y1, p.y2, p.s11, p.s22, p.s12)
      fit.bnm_p  <- nlminb(bnm.int, fn.bnm.ml,
                           lower = c(rep(-Inf,2), rep(0, 2),  -1),
                           upper = c(rep( Inf,2), rep(Inf, 2), 0) 
                           )

      if(!inherits(fit.bnm_p, "try-error")) {
        
        bnm.p <- c(fit.bnm_p$par)
        SROC(bnm.p, sroc = "sroc", add = TRUE, ncols = "grey")
          
        }  
      } 
      
    ## 2 BNM.O ----
    
    {
      fn.bnm.ml  <- function(par) llk.BNM.ml(par, o.y1, o.y2, o.s11, o.s22, o.s12)
      
      fit.bnm_o  <- nlminb(bnm.int, fn.bnm.ml,
                           lower = c(rep(-Inf,2), rep(0, 2),  -1),
                           upper = c(rep( Inf,2), rep(Inf, 2), 0) 
                           )

      if(!inherits(fit.bnm_o, "try-error")) {
        
        bnm.o <- c(fit.bnm_o$par)
        SROC(bnm.o, sroc = "sroc", add = TRUE)
      } 
    }
  
    
     ## 3 TNM.SA  ----
    
    {
      fn.tnm.ml  <- function(par) clk.TNM.ml(par, o.y1, o.y2, o.y3, o.s11, o.s22, o.s33, o.s12, o.s13, o.s23, p=0.6, a.interval = c(-10, 10))

      #tnm.int
      fit.tnm_sa <- nlminb(
        c(tnm.int, 0.5), fn.tnm.ml,
        lower = c(rep(-Inf,2), 0, rep(0, 3), rep(-1,3), 0),
        upper = c(rep( Inf,2), Inf, rep(Inf, 3), rep( 1,3), 2) )

      if(!inherits(fit.tnm_sa, "try-error")) {

        conv  <- fit.tnm_sa$convergence
        tnm.sa <- fit.tnm_sa$par[c(1,2,4,5,7)]  # u1 u2 t1 t2 r1
        SROC(tnm.sa, sroc = "sroc", add = TRUE, ncols = 2)

      }
    }

    
    
res <- rma(yi = u_lnHR, vi = v_lnHR, data=dataSt.o)
tf <- trimfill(res)
funnel(tf, ylab = "Observed lnHR", back="white")
points(dataSt.p$u_lnHR, sqrt(dataSt.p$v_lnHR), col="grey", pch = 19)


tf.y.obs <- tf$yi[!tf$fill]
tf.v.obs <- tf$vi[!tf$fill]
points(tf.y.obs, sqrt(tf.v.obs), col="black", pch = 19)

tf.y.fill <- tf$yi[tf$fill]
tf.v.fill <- tf$vi[tf$fill]
points(tf.y.fill, sqrt(tf.v.fill))

legend("topleft", legend = c("Observed", "Unobserved", "Filled"), 
       pch = c(19,19,1),
       col = c("grey", "black", "black"))

    par(mfrow = c(1,1))



}
```


```{r, fig.width=12, fig.height=6}
set.seed(100)
SROC.tstat(path ="a-calc/beta1_pts50_300.RData", S=60, mk.id=1, a=-2.1)
```


```{r, fig.width=12, fig.height=6}
set.seed(123)
SROC.tstat(path ="a-calc/beta1_pts50_300.RData", S=60, mk.id=2, a=-1.1)
```


```{r, fig.width=12, fig.height=6}
set.seed(100)
SROC.tstat(path ="a-calc/beta1_pts50_300.RData", S=100, mk.id=1, a=-2.3)
```


```{r, fig.width=12, fig.height=6}
set.seed(100)
SROC.tstat(path ="a-calc/beta1_pts50_300.RData", S=100, mk.id=2, a=-0.8)
```

