---
title: "Simulation Result 1: Exp(0.2), 5 methods comparison"
author: "Yi"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
options(knitr.kable.NA = '')
library(knitr)
library(kableExtra)
library(tidyverse)
library(wrapr)
library(ggplot2)
library(gridExtra)

rm(list = ls())

```

```{r}
load("a-calc/beta1_pts50_150.RData")
set
load("a-calc/beta1_pts50_300.RData")
set
```


```{r, include=FALSE}
dimname.sauc <- list(NULL, c("M1BNM.P", "M2BNM.O", "M3TNM.P", "M4TNM.O","M5TNM.Prop"))
dimname.par <- list(
  c("mu1", "mu2", "mu3", "tau1", "tau2", "tau3", "rho1", "rho2", "rho3", 
      "beta", "alpha","S","N","prop","sauc","nc"), 
  c("M1BNM.P", "M2BNM.O", "M3TNM.P", "M4TNM.O","M5TNM.Prop"))
dimname.sauc.med <- list(c("M1BNM.P", "M2BNM.O", "M3TNM.P", "M4TNM.O","M5TNM.Prop"), 
                         c("Median (Q1, Q3)"))
dimname.sauc.msd <- list(c("M1BNM.P", "M2BNM.O", "M3TNM.P", "M4TNM.O","M5TNM.Prop"), 
                         c("Mean (SD)"))

result_list <- function(path = "N30/ptdis1_HR1_p0.1.RData", only.conv = TRUE){ 

  load(path)
  if(only.conv){
    
    nconv <- DATA[16,]!=0
    DATA[1:15, nconv] <- NA
    
  }
  ncv <- sum(!complete.cases(DATA[1,]))
  
  sauc.val <- matrix(DATA[15,], ncol = 5, byrow = TRUE, 
                  dimnames = dimname.sauc)
  
  ## convergence rate
  cv   <- matrix(DATA[16,], ncol = 5, byrow = TRUE)
  cv.sum  <- sapply(1:5, function(i) sum(1-cv[,i], na.rm = TRUE)/10)
  
  # MED pf pars
  dim(DATA) <- c(16, 5, dim(DATA)[2]/5)
  med <- apply(DATA, 1:2, function(x) median(x, na.rm = TRUE))
  q1  <- apply(DATA, 1:2, function(x) quantile(x, probs = 0.25, na.rm = TRUE))
  q3  <- apply(DATA, 1:2, function(x) quantile(x, probs = 0.75, na.rm = TRUE))
  
  mean <- apply(DATA, 1:2, function(x) mean(x, na.rm = TRUE))
  sd   <- apply(DATA, 1:2, function(x) sd(x, na.rm = TRUE))
  
  par.med.q13 <- matrix(sprintf("%.2f (%.2f, %.2f)", med, q1, q3), 16,5, 
                        dimnames = dimname.par)[c(1:11),]
  sauc.med.q13 <- matrix(sprintf("%.2f (%.2f, %.2f)", med*100, q1*100, q3*100), 16,5, 
                        dimnames = dimname.par)[c(15),]
  par.mean.sd <- matrix(sprintf("%.2f (%.2f)", mean, sd), 16,5,
                        dimnames = dimname.par)[-c(1:11, 15),]

  
  return(list(sauc.val = sauc.val, 
              cv.sum= cv.sum, 
              par.mean.sd = par.mean.sd,
              par.med.q13 = par.med.q13, 
              sauc.med.q13 = sauc.med.q13,
              rm.ncv = ncv))
}
```


```{r, include=FALSE}
grp.bp <- function(
    data1, data2, data3, data4, data5, data6, data7, data8, data9,
    pS.lab,
    title = "N = 30",
    ylim = c(0, 1)){
  
data11 <- data.frame(data1$sauc.val, p = rep(pS.lab[1], nrow(data1$sauc.val)))
data22 <- data.frame(data2$sauc.val, p = rep(pS.lab[2], nrow(data2$sauc.val)))
data33 <- data.frame(data3$sauc.val, p = rep(pS.lab[3], nrow(data3$sauc.val)))
data44 <- data.frame(data4$sauc.val, p = rep(pS.lab[4], nrow(data4$sauc.val)))
data55 <- data.frame(data5$sauc.val, p = rep(pS.lab[5], nrow(data5$sauc.val)))
data66 <- data.frame(data6$sauc.val, p = rep(pS.lab[6], nrow(data6$sauc.val)))
data77 <- data.frame(data7$sauc.val, p = rep(pS.lab[7], nrow(data7$sauc.val)))
data88 <- data.frame(data8$sauc.val, p = rep(pS.lab[8], nrow(data8$sauc.val)))
data99 <- data.frame(data9$sauc.val, p = rep(pS.lab[9], nrow(data9$sauc.val)))

sauc <- rbind.data.frame(data11, data22, data33, data44, data55,
                         data66, data77, data88, data99)

sauc %>% 
  mutate(p = factor(p , levels=c(pS.lab))) %>% 
  pivot_longer(cols = -p, names_to = "Model") %>% 
  ggplot(aes(x = p, y = value, fill = Model)) + 
  geom_boxplot(notch=FALSE, notchwidth = 0.5, outlier.shape = NA, alpha = 0.7) +
  scale_y_continuous(name = "SAUC", limits=ylim)+
  scale_x_discrete(name = "p(S)")+
  # stat_summary(fun="mean", fun.args = list(na.rm = TRUE), 
  #              geom="point", shape=18, size=2, color="red",
  #            position = position_dodge2(width = 0.75, preserve = "single"))+
  ggtitle(title) +
  scale_fill_grey() +
  theme_light() +
  theme(legend.position = "none", plot.title = element_text(hjust = 0.5, face="plain", size =11))
  # geom_hline(yintercept=median(data1$sauc.val[,1], na.rm = TRUE)) +
  # geom_hline(yintercept=median(data1$sauc.val[,3], na.rm = TRUE))
  
}

```



```{r, include=FALSE}
## PT DISTRIBUTION 1 ----

## N20 -------------------------------------------------------------------------
# HR1 -------------------------------------------------------------------------
N20.09 <- result_list("N20/ptdis1_HR1_p0.9.RData")
N20.08 <- result_list("N20/ptdis1_HR1_p0.8.RData")
N20.07 <- result_list("N20/ptdis1_HR1_p0.7.RData")
N20.06 <- result_list("N20/ptdis1_HR1_p0.6.RData")
N20.05 <- result_list("N20/ptdis1_HR1_p0.5.RData")
N20.04 <- result_list("N20/ptdis1_HR1_p0.4.RData")
N20.03 <- result_list("N20/ptdis1_HR1_p0.3.RData")
N20.02 <- result_list("N20/ptdis1_HR1_p0.2.RData") 
N20.01 <- result_list("N20/ptdis1_HR1_p0.1.RData")

# HR2 --------------------------------------------------------------------------

N20.09.2 <- result_list("N20/ptdis1_HR2_p0.9.RData")
N20.08.2 <- result_list("N20/ptdis1_HR2_p0.8.RData")
N20.07.2 <- result_list("N20/ptdis1_HR2_p0.7.RData")
N20.06.2 <- result_list("N20/ptdis1_HR2_p0.6.RData")
N20.05.2 <- result_list("N20/ptdis1_HR2_p0.5.RData")
N20.04.2 <- result_list("N20/ptdis1_HR2_p0.4.RData")
N20.03.2 <- result_list("N20/ptdis1_HR2_p0.3.RData")
N20.02.2 <- result_list("N20/ptdis1_HR2_p0.2.RData") 
N20.01.2 <- result_list("N20/ptdis1_HR2_p0.1.RData")

## N30 -------------------------------------------------------------------------
# HR1 --------------------------------------------------------------------------
N30.09 <- result_list("N30/ptdis1_HR1_p0.9.RData")
N30.08 <- result_list("N30/ptdis1_HR1_p0.8.RData")
N30.07 <- result_list("N30/ptdis1_HR1_p0.7.RData")
N30.06 <- result_list("N30/ptdis1_HR1_p0.6.RData")
N30.05 <- result_list("N30/ptdis1_HR1_p0.5.RData")
N30.04 <- result_list("N30/ptdis1_HR1_p0.4.RData")
N30.03 <- result_list("N30/ptdis1_HR1_p0.3.RData")
N30.02 <- result_list("N30/ptdis1_HR1_p0.2.RData") 
N30.01 <- result_list("N30/ptdis1_HR1_p0.1.RData")

## HR2 -------------------------------------------------------------------------

N30.09.2 <- result_list("N30/ptdis1_HR2_p0.9.RData")
N30.08.2 <- result_list("N30/ptdis1_HR2_p0.8.RData")
N30.07.2 <- result_list("N30/ptdis1_HR2_p0.7.RData")
N30.06.2 <- result_list("N30/ptdis1_HR2_p0.6.RData")
N30.05.2 <- result_list("N30/ptdis1_HR2_p0.5.RData")
N30.04.2 <- result_list("N30/ptdis1_HR2_p0.4.RData")
N30.03.2 <- result_list("N30/ptdis1_HR2_p0.3.RData")
N30.02.2 <- result_list("N30/ptdis1_HR2_p0.2.RData") 
N30.01.2 <- result_list("N30/ptdis1_HR2_p0.1.RData")


## N=50 ------------------------------------------------------------------------

N50.09 <- result_list("N50/ptdis1_HR1_p0.9.RData")
N50.08 <- result_list("N50/ptdis1_HR1_p0.8.RData")
N50.07 <- result_list("N50/ptdis1_HR1_p0.7.RData")
N50.06 <- result_list("N50/ptdis1_HR1_p0.6.RData")
N50.05 <- result_list("N50/ptdis1_HR1_p0.5.RData")
N50.04 <- result_list("N50/ptdis1_HR1_p0.4.RData")
N50.03 <- result_list("N50/ptdis1_HR1_p0.3.RData")
N50.02 <- result_list("N50/ptdis1_HR1_p0.2.RData") 
N50.01 <- result_list("N50/ptdis1_HR1_p0.1.RData")


N50.09.2 <- result_list("N50/ptdis1_HR2_p0.9.RData")
N50.08.2 <- result_list("N50/ptdis1_HR2_p0.8.RData")
N50.07.2 <- result_list("N50/ptdis1_HR2_p0.7.RData")
N50.06.2 <- result_list("N50/ptdis1_HR2_p0.6.RData")
N50.05.2 <- result_list("N50/ptdis1_HR2_p0.5.RData")
N50.04.2 <- result_list("N50/ptdis1_HR2_p0.4.RData")
N50.03.2 <- result_list("N50/ptdis1_HR2_p0.3.RData")
N50.02.2 <- result_list("N50/ptdis1_HR2_p0.2.RData") 
N50.01.2 <- result_list("N50/ptdis1_HR2_p0.1.RData")


```


## Plot

```{r, fig.width=12, fig.height=18}

p1 <- grp.bp(N30.09, N30.08, N30.07, N30.06, N30.05, N30.04, N30.03, N30.02, N30.01,
             pS.lab = as.character(seq(0.9, 0.1, -0.1)), 
             title = "N = 30, HR1", ylim = c(0,1))

p2 <- grp.bp(N30.09.2, N30.08.2, N30.07.2, N30.06.2, N30.05.2, N30.04.2, N30.03.2, N30.02.2, N30.01.2,
             pS.lab = as.character(seq(0.9, 0.1, -0.1)), 
             title = "N = 30, HR2", ylim = c(0,1))

p3 <- grp.bp(N50.09, N50.08, N50.07, N50.06, N50.05, N50.04, N50.03, N50.02, N50.01,
             pS.lab = as.character(seq(0.9, 0.1, -0.1)), 
             title = "N = 50, HR1", ylim = c(0,1))

p4 <- grp.bp(N50.09.2, N50.08.2, N50.07.2, N50.06.2, N50.05.2, N50.04.2, N50.03.2, N50.02.2, N50.01.2,
             pS.lab = as.character(seq(0.9, 0.1, -0.1)), 
             title = "N = 50, HR2", ylim = c(0,1))

p5 <- grp.bp(N20.09, N20.08, N20.07, N20.06, N20.05, N20.04, N20.03, N20.02, N20.01,
             pS.lab = as.character(seq(0.9, 0.1, -0.1)), 
             title = "N = 50, HR1", ylim = c(0,1))

p6 <- grp.bp(N20.09.2, N20.08.2, N20.07.2, N20.06.2, N20.05.2, N20.04.2, N20.03.2, N20.02.2, N20.01.2,
             pS.lab = as.character(seq(0.9, 0.1, -0.1)), 
             title = "N = 50, HR2", ylim = c(0,1))



grid.arrange(p5, p6, p1, p2, p3, p4, nrow=3)
```


## Tab1

```{r}
sauc.mq.20 <- cbind.data.frame(
  N = c(20, NA, NA, NA, NA),
  Methods = c("BNM$_P$", "BNM$_O$", "TNM$_P$", "TNM$_O$", "Prop"),
  N20.09$sauc.med.q13, N20.08$sauc.med.q13, N20.07$sauc.med.q13, N20.06$sauc.med.q13,
  N20.05$sauc.med.q13, N20.04$sauc.med.q13, N20.03$sauc.med.q13, N20.02$sauc.med.q13,
  N20.01$sauc.med.q13)

sauc.mq.20.2 <- cbind.data.frame(
  N = c(20, NA, NA, NA, NA),
  Methods = c("BNM$_P$", "BNM$_O$", "TNM$_P$", "TNM$_O$", "Prop"),
  N20.09.2$sauc.med.q13, N20.08.2$sauc.med.q13, N20.07.2$sauc.med.q13, N20.06.2$sauc.med.q13,
  N20.05.2$sauc.med.q13, N20.04.2$sauc.med.q13, N20.03.2$sauc.med.q13, N20.02.2$sauc.med.q13,
  N20.01.2$sauc.med.q13)

sauc.mq.20
sauc.mq.20.2

sauc.mq.30 <- cbind.data.frame(
  N = c(30, NA, NA, NA, NA),
  Methods = c("BNM$_P$", "BNM$_O$", "TNM$_P$", "TNM$_O$", "Prop"),
  N30.09$sauc.med.q13, N30.08$sauc.med.q13, N30.07$sauc.med.q13, N30.06$sauc.med.q13,
  N30.05$sauc.med.q13, N30.04$sauc.med.q13, N30.03$sauc.med.q13, N30.02$sauc.med.q13,
  N30.01$sauc.med.q13)

sauc.mq.30.2 <- cbind.data.frame(
  N = c(30, NA, NA, NA, NA),
  Methods = c("BNM$_P$", "BNM$_O$", "TNM$_P$", "TNM$_O$", "Prop"),
  N30.09.2$sauc.med.q13, N30.08.2$sauc.med.q13, N30.07.2$sauc.med.q13, N30.06.2$sauc.med.q13,
  N30.05.2$sauc.med.q13, N30.04.2$sauc.med.q13, N30.03.2$sauc.med.q13, N30.02.2$sauc.med.q13,
  N30.01.2$sauc.med.q13)

sauc.mq.30
sauc.mq.30.2

sauc.mq.50 <- cbind.data.frame(
  N = c(50, NA, NA, NA, NA),
  Methods = c("BNM$_P$", "BNM$_O$", "TNM$_P$", "TNM$_O$", "Prop"),
  N50.09$sauc.med.q13, N50.08$sauc.med.q13, N50.07$sauc.med.q13, N50.06$sauc.med.q13,
  N50.05$sauc.med.q13, N50.04$sauc.med.q13, N50.03$sauc.med.q13, N50.02$sauc.med.q13,
  N50.01$sauc.med.q13)

sauc.mq.50.2 <- cbind.data.frame(
  N = c(50, NA, NA, NA, NA),
  Methods = c("BNM$_P$", "BNM$_O$", "TNM$_P$", "TNM$_O$", "Prop"),
  N50.09.2$sauc.med.q13, N50.08.2$sauc.med.q13, N50.07.2$sauc.med.q13, N50.06.2$sauc.med.q13,
  N50.05.2$sauc.med.q13, N50.04.2$sauc.med.q13, N50.03.2$sauc.med.q13, N50.02.2$sauc.med.q13,
  N50.01.2$sauc.med.q13)

sauc.mq.50
sauc.mq.50.2

```


```{r}
cv.20 <- data.frame(N20.09$cv.sum, N20.08$cv.sum, N20.07$cv.sum, N20.06$cv.sum,
                    N20.05$cv.sum, N20.04$cv.sum, N20.03$cv.sum, N20.02$cv.sum, 
                    N20.01$cv.sum) 
cv.20.2 <- data.frame(N20.09.2$cv.sum, N20.08.2$cv.sum, N20.07.2$cv.sum, N20.06.2$cv.sum,
                      N20.05.2$cv.sum, N20.04.2$cv.sum, N20.03.2$cv.sum, N20.02.2$cv.sum, 
                      N20.01.2$cv.sum) 

cv.30 <- data.frame(N30.09$cv.sum, N30.08$cv.sum, N30.07$cv.sum, N30.06$cv.sum,
                    N30.05$cv.sum, N30.04$cv.sum, N30.03$cv.sum, N30.02$cv.sum, 
                    N30.01$cv.sum) 
cv.30.2 <- data.frame(N30.09.2$cv.sum, N30.08.2$cv.sum, N30.07.2$cv.sum, N30.06.2$cv.sum,
                      N30.05.2$cv.sum, N30.04.2$cv.sum, N30.03.2$cv.sum, N30.02.2$cv.sum, 
                      N30.01.2$cv.sum) 

cv.50 <- data.frame(N50.09$cv.sum, N50.08$cv.sum, N50.07$cv.sum, N50.06$cv.sum,
                    N50.05$cv.sum, N50.04$cv.sum, N50.03$cv.sum, N50.02$cv.sum, 
                    N50.01$cv.sum) 
cv.50.2 <- data.frame(N50.09.2$cv.sum, N50.08.2$cv.sum, N50.07.2$cv.sum, N50.06.2$cv.sum,
                      N50.05.2$cv.sum, N50.04.2$cv.sum, N50.03.2$cv.sum, N50.02.2$cv.sum, 
                      N50.01.2$cv.sum)  

cv.20
cv.20.2
cv.30
cv.30.2
cv.50
cv.50.2
```
