---
title: "Simulation Result 4: U(1,3)"
author: "Yi"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
options(knitr.kable.NA = '')
library(knitr)
library(kableExtra)
library(tidyverse)
library(ggpubr)
rm(list = ls())
load("a-calc/beta_1_alpha_20.RData")
save.tex <- TRUE
```

Notation: 

- $T$: time-to-event

- $X^{(s)}_i$: the biomarker measure of $i$th person in the $s$th study


# 1 Samll HR


Simulation scenario 1

- If $T ≤ 2$, $X^{(s)}_i\sim 0.7 + 0.1e_i^{(s)}$

- If $T > 2$, $X^{(s)}_i\sim 0.3 + 0.3e_i^{(s)}$

- $e_i^{(s)} \sim logistic(n^{(s)})$

- $n^{(s)}\sim unif[50, 150]$

- $\beta = 1,~\alpha$ = `r round(set[["alpha1"]],3)`

```{r, include=FALSE}

dimname.sauc <- list(NULL, c("BNM.Pop", "BNM.Pub", "TNM.Prop"))
dimname.par <- list(c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3", "b"), c("BNM.Pop", "BNM.Pub", "TNM.Prop"))
dimname.sauc.med <- list(c("BNM.Pop", "BNM.Pub", "TNM.Prop"), c("Median (Q1, Q3)"))

result_list <- function(path = "N20/HR1_p0.8.RData"){ 

  load(path)
  sauc.val <- matrix(DATA[11,], ncol = 3, byrow = TRUE, 
                  dimnames = dimname.sauc)
  
  ## convergence rate
  cv   <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
  cv.sum  <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)
  
  ## proportion, S/N/p
  pro  <- matrix(DATA[12,], ncol = 3, byrow = TRUE)
  pro.sum <- sapply(1:3, function(i) mean(pro[,i], na.rm = TRUE))
  
  # MED pf pars
  dim(DATA) <- c(13, 3, dim(DATA)[2]/3)
  med <- apply(DATA, 1:2, function(x) median(x, na.rm = TRUE))[-c(12,13),]
  q1  <- apply(DATA, 1:2, function(x) quantile(x, probs = 0.25, na.rm = TRUE))[-c(12,13),]
  q3  <- apply(DATA, 1:2, function(x) quantile(x, probs = 0.75, na.rm = TRUE))[-c(12,13),]
  
  par.med.q13 <- matrix(sprintf("%.2f (%.2f, %.2f)", med[-11,], q1[-11,], q3[-11,]), 10,3, dimnames = dimname.par)
  sauc.med.q13 <- matrix(sprintf("%.1f (%.1f, %.1f)", 100*med[11,], 100*q1[11,], 100*q3[11,]), 3,1, dimnames = dimname.sauc.med)
  
  return(list(sauc.val = sauc.val, cv.sum= cv.sum, pro.sum = pro.sum, 
              par.med.q13 = par.med.q13, sauc.med.q13 = sauc.med.q13))
}

# N=20 -------------------------------------------------------------------------

n20.08 <- result_list("N20/HR1_p0.8.RData")
n20.06 <- result_list("N20/HR1_p0.6.RData")
n20.04 <- result_list("N20/HR1_p0.4.RData")
n20.02 <- result_list("N20/HR1_p0.2.RData") 
n20.02$sauc.val <- rbind(rep(NA, 3),rep(NA, 3),rep(NA, 3), n20.02$sauc.val)



# N=30 -------------------------------------------------------------------------


n30.08 <- result_list("N30/HR1_p0.8.RData")
n30.06 <- result_list("N30/HR1_p0.6.RData")
n30.04 <- result_list("N30/HR1_p0.4.RData")
n30.02 <- result_list("N30/HR1_p0.2.RData") 


# N=50 -------------------------------------------------------------------------


n50.08 <- result_list("N50/HR1_p0.8.RData")
n50.06 <- result_list("N50/HR1_p0.6.RData")
n50.04 <- result_list("N50/HR1_p0.4.RData")
n50.02 <- result_list("N50/HR1_p0.2.RData") 


```


## Plot

```{r}
## N = 20

grp.bp <- function(
    data1, data2, data3, data4, 
    pS.lab = c("0.8(25)", "0.6(33)", "0.4(50)", "0.2(100)"),
    title = "N = 20",
    ylim = c(0.6, 0.9)){
  
sauc <- rbind.data.frame(data1$sauc.val, data2$sauc.val, data3$sauc.val, data4$sauc.val)
sauc$p <- rep(pS.lab, each = 1000)
sauc %>% 
  mutate(p = factor(p , levels=c(pS.lab))) %>% 
  pivot_longer(cols = -p, names_to = "Model") %>% 
  ggplot(aes(x = p, y = value, fill = Model)) + 
  geom_boxplot(notch=TRUE, notchwidth = 0.5, outlier.shape = NA, alpha = 0.7) +
  scale_y_continuous(name = "SAUC", limits=ylim)+
  scale_x_discrete(name = "p(S)")+
  stat_summary(fun=mean, fun.args = list(na.rm = TRUE), 
               geom="point", shape=18, size=2, color="red",
             position = position_dodge2(width = 0.75, preserve = "single"))+
  ggtitle(title) +
  scale_fill_grey() +
  theme_light() +
  theme(legend.position = "none", plot.title = element_text(hjust = 0.5, face="plain", size =11))
  
}

p1 <- grp.bp(n20.08, n20.06, n20.04, n20.02, pS.lab = c("0.8(25)", "0.6(33)", "0.4(50)", "0.2(100)"), title = "N = 20")
p2 <- grp.bp(n30.08, n30.06, n30.04, n30.02, pS.lab = c("0.8(38)", "0.6(50)", "0.4(75)", "0.2(150)"), title = "N = 30")
p3 <- grp.bp(n50.08, n50.06, n50.04, n50.02, pS.lab = c("0.8(63)", "0.6(83)", "0.4(125)", "0.2(250)"),title = "N = 50")
```


## Tab1

```{r}
sauc1 <- cbind.data.frame(N = c(20, NA, NA),
                         Methods = c("BNM$_P$", "BNM$_O$", "Prop"),
                         n20.08$sauc.med.q13, n20.06$sauc.med.q13, n20.04$sauc.med.q13, n20.02$sauc.med.q13)
cr1 <- c(NA, "CR", n20.08$cv.sum[3], n20.06$cv.sum[3], n20.04$cv.sum[3], n20.02$cv.sum[3])

sauc2 <- cbind.data.frame(N = c(30, NA, NA),
                         Methods = c("BNM$_P$", "BNM$_O$", "Prop"),
                         n30.08$sauc.med.q13, n30.06$sauc.med.q13, n30.04$sauc.med.q13, n30.02$sauc.med.q13)
cr2 <- c(NA, "CR", n30.08$cv.sum[3], n30.06$cv.sum[3], n30.04$cv.sum[3], n30.02$cv.sum[3])

sauc3 <- cbind.data.frame(N = c(50, NA, NA),
                         Methods = c("BNM$_P$", "BNM$_O$", "Prop"),
                         n50.08$sauc.med.q13, n50.06$sauc.med.q13, n50.04$sauc.med.q13, n50.02$sauc.med.q13)
cr3 <- c(NA, "CR", n50.08$cv.sum[3], n50.06$cv.sum[3], n50.04$cv.sum[3], n50.02$cv.sum[3])

sauc <- rbind.data.frame(sauc1, cr1, sauc2, cr2, sauc3, cr3)
rownames(sauc) <- NULL
```


```{r}
if (save.tex) sink("tb-sauc-s4-1.tex")

sauc %>%
  kbl(
    caption ="Summary of the tSAUC when HR is small", 
    format = ifelse(save.tex, "latex", "html"),
    longtable = F, 
    booktabs = T,
    align = "r",
    position = "!htb",
    linesep = c('', '', '', '\\addlinespace'),
    escape = FALSE,
    label = "sauc.med.1",) %>%
  add_header_above(c("", "", "$p = 0.8$", "$p = 0.6$", "$p = 0.4$", "$p = 0.2$"),escape = FALSE) %>%
  footnote(general = "
Median with 25th empirical quartile (Q1) and 75th empirical quartile (Q3) of the tSAUC are reported. 
$N$ denotes the number of the published studies. 
BNM$_P$ denotes the BNM model without PB; 
BNM$_O$ denotes the BNM model with PB;
Prop denotes the proposed model.
CR denotes the proportion of convergence times of the proposed model among 1000 simulations.
All the entries are multiplied by 100.", 
   escape = FALSE, threeparttable = TRUE,  general_title = "")
if (save.tex)  sink()

```

# 2 Moderate HR

Simulation scenario

- If $T ≤ 2$, $X^{(s)}_i\sim 0.7 + 0.1e_i^{(s)}$

- If $T > 2$, $X^{(s)}_i\sim 0.1 + 0.5e_i^{(s)}$

- $\beta = 1,~\alpha$ = `r round(set[["alpha2"]],3)`

```{r}

# N=20 -------------------------------------------------------------------------

n20.08.2 <- result_list("N20/HR2_p0.8.RData")
n20.06.2 <- result_list("N20/HR2_p0.6.RData")
n20.04.2 <- result_list("N20/HR2_p0.4.RData")
n20.02.2 <- result_list("N20/HR2_p0.2.RData") 


# N=30 -------------------------------------------------------------------------


n30.08.2 <- result_list("N30/HR2_p0.8.RData")
n30.06.2 <- result_list("N30/HR2_p0.6.RData")
n30.04.2 <- result_list("N30/HR2_p0.4.RData")
n30.02.2 <- result_list("N30/HR2_p0.2.RData") 


# N=50 -------------------------------------------------------------------------


n50.08.2 <- result_list("N50/HR2_p0.8.RData")
n50.06.2 <- result_list("N50/HR2_p0.6.RData")
n50.04.2 <- result_list("N50/HR2_p0.4.RData")
n50.02.2 <- result_list("N50/HR2_p0.2.RData") 



```

## Plot2

```{r,fig.width = 9, fig.height = 9}
p4 <- grp.bp(n20.08.2, n20.06.2, n20.04.2, n20.02.2, pS.lab = c("0.8(25)", "0.6(33)", "0.4(50)", "0.2(100)"), title = "N = 20", ylim = c(0.4, 0.8))
p5 <- grp.bp(n30.08.2, n30.06.2, n30.04.2, n30.02.2, pS.lab = c("0.8(38)", "0.6(50)", "0.4(75)", "0.2(150)"), title = "N = 30", ylim = c(0.4, 0.8))
p6 <- grp.bp(n50.08.2, n50.06.2, n50.04.2, n50.02.2, pS.lab = c("0.8(63)", "0.6(83)", "0.4(125)", "0.2(250)"),title = "N = 50", ylim = c(0.4, 0.8))

```


## Tab2

```{r}
sauc4 <- cbind.data.frame(N = c(20, NA, NA),
                         Methods = c("BNM$_P$", "BNM$_O$", "Prop"),
                         n20.08.2$sauc.med.q13, n20.06.2$sauc.med.q13, n20.04.2$sauc.med.q13, n20.02.2$sauc.med.q13)
cr4 <- c(NA, "CR", n20.08.2$cv.sum[3], n20.06.2$cv.sum[3], n20.04.2$cv.sum[3], n20.02.2$cv.sum[3])

sauc5 <- cbind.data.frame(N = c(30, NA, NA),
                         Methods = c("BNM$_P$", "BNM$_O$", "Prop"),
                         n30.08.2$sauc.med.q13, n30.06.2$sauc.med.q13, n30.04.2$sauc.med.q13, n30.02.2$sauc.med.q13)
cr5 <- c(NA, "CR", n30.08.2$cv.sum[3], n30.06.2$cv.sum[3], n30.04.2$cv.sum[3], n30.02.2$cv.sum[3])

sauc6 <- cbind.data.frame(N = c(50, NA, NA),
                         Methods = c("BNM$_P$", "BNM$_O$", "Prop"),
                         n50.08.2$sauc.med.q13, n50.06.2$sauc.med.q13, n50.04.2$sauc.med.q13, n50.02.2$sauc.med.q13)
cr6 <- c(NA, "CR", n50.08.2$cv.sum[3], n50.06.2$cv.sum[3], n50.04.2$cv.sum[3], n50.02.2$cv.sum[3])

sauc2 <- rbind.data.frame(sauc4, cr4, sauc5, cr5, sauc6, cr6)
rownames(sauc2) <- NULL
```


```{r}
if (save.tex) sink("tb-sauc-s4-2.tex")

sauc2 %>%
  kbl(
    caption ="Summary of the tSAUC when HR is moderate", 
    format = ifelse(save.tex, "latex", "html"),
    longtable = F, 
    booktabs = T,
    align = "r",
    position = "!htb",
    linesep = c('', '', '', '\\addlinespace'),
    escape = FALSE,
    label = "sauc.med.2",) %>%
  add_header_above(c("", "", "$p = 0.8$", "$p = 0.6$", "$p = 0.4$", "$p = 0.2$"),escape = FALSE) %>%
  footnote(general = "
Median with 25th empirical quartile (Q1) and 75th empirical quartile (Q3) of the tSAUC are reported. 
$N$ denotes the number of the published studies. 
BNM$_P$ denotes the BNM model without PB; 
BNM$_O$ denotes the BNM model with PB;
Prop denotes the proposed model.
CR denotes the proportion of convergence times of the proposed model among 1000 simulations.
All the entries are multiplied by 100.", 
   escape = FALSE, threeparttable = TRUE,  general_title = "") 
if (save.tex)  sink()

```

# Plot all

```{r}
ggarrange(p1, p2, p3, p4, p5, p6, ncol = 3, nrow=2,labels = LETTERS[1:6],
          common.legend = TRUE, legend = "bottom",
          font.label = list(size = 12, face = "plain"))
```

