---
title: "PAR-b1-N50-8res"
author: "Yi"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.width = 5, fig.height = 5)
options(knitr.kable.NA = '')
library(knitr)
library(kableExtra)
```

## Median

pts$\sim U[30, 50]$

```{r, echo=FALSE}
load("resb1/DATA_N50_HR1_p0.9.RData")

source("res.par.med8.R")

kbl(x, caption = "p = 0.9")%>%
  kable_classic(full_width = F, html_font = "Cambria")
	

load("resb1/DATA_N50_HR1_p0.7.RData")

source("res.par.med8.R")

kbl(x, caption = "p = 0.7")%>%
  kable_classic(full_width = F, html_font = "Cambria")
	

load("resb1/DATA_N50_HR1_p0.5.RData")

source("res.par.med8.R")

kbl(x, caption = "p = 0.6")%>%
  kable_classic(full_width = F, html_font = "Cambria")
	

load("resb1/DATA_N50_HR1_p0.3.RData")

source("res.par.med8.R")

kbl(x, caption = "p = 0.3")%>%
  kable_classic(full_width = F, html_font = "Cambria")
	

load("resb1/DATA_N50_HR1_p0.1.RData")

source("res.par.med8.R")

kbl(x, caption = "p = 0.1")%>%
  kable_classic(full_width = F, html_font = "Cambria")
	
```
