---
title: 'Simulation Result 1: C~Exp(0.2)'
author: "Yi"
date: "`r Sys.Date()`"
output:
  pdf_document: default
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
options(knitr.kable.NA = '')
library(knitr)
library(kableExtra)
library(tidyverse)

# library(ggpubr)
rm(list = ls())
save.tex <- F
```



```{r, include=FALSE}

## FUNCTION FOR CREATING OBJECT

dimname.sauc <- list(c("M1BNM.P", "M2BNM.O", "M3TNM.P", "M4TNM.O","M5TNM.Prop"), "tSAUC")
# dimname.cr   <- list(c("M1BNM.P", "M2BNM.O", "M3TNM.P", "M4TNM.O","M5TNM.Prop"), "CR")

# dimname.par <- list(c("u1", "u2", "u3", "t1", "t2", "t3", "r1", "r2", "r3", "b"), c("BNM.Pop", "BNM.Pub", "TNM.Prop"))
# dimname.sauc.med <- list(c("BNM.Pop", "BNM.Pub", "TNM.Prop"), c("Median (Q1, Q3)"))

result_list <- function(path = "exp0.2/N20/ptdis2_HR1_p0.8.RData", dnm.cr = dimname.cr, dnm.sauc = dimname.sauc){ 

  load(path)
  
  # ## convergence rate
  # cr   <- matrix(DATA[16,], ncol = 5, byrow = TRUE)
  # cr.sum  <- matrix(sapply(1:5, function(i) sum(1-cr[,i], na.rm = TRUE)/10),5,1, dimnames = dnm.cr)
  
  # MED pf sauc
  sauc.val <- matrix(DATA[15,], ncol = 5, byrow = TRUE)
  succ <- nrow(sauc.val)/10
  
  med <- apply(sauc.val, 2, function(x) median(x, na.rm = TRUE))*100
  q1  <- apply(sauc.val, 2, function(x) quantile(x, probs = 0.25, na.rm = TRUE))*100
  q3  <- apply(sauc.val, 2, function(x) quantile(x, probs = 0.75, na.rm = TRUE))*100
  
  sauc.med.q13 <- matrix(sprintf("%.2f (%.2f, %.2f)", med, q1, q3), 5,1, dimnames = dnm.sauc)

  
  return(list(sauc.med.q13 = sauc.med.q13, succ = succ))
}
```


```{r, include=FALSE}

## CREATE OBJECT
## OBJECT NAME EXAMPLE: N20.D1.HR1.P0.8

for(folder in c("exp0.2/", "U14/")){
	
	for(N in c("N20", "N30", "N50")){
	
	for(ptdist in 1:2){
		
		for(HR in 1:3){
			
			for(p in seq(0.7, 0.3, -0.2)) {
				
				if (folder=="exp0.2/") fd <- "F1." else fd <- "F2."
				assign(paste0(fd, N, ".D", ptdist, ".HR", HR, ".P", p), 
											result_list(paste0(folder, N, "/ptdis", ptdist, "_HR", HR, "_p", p, ".RData")) )
			}
		}
	}
}
	
}

```



```{r}

## FUNCTION FOR CREATING SMALL TABLES

tsauc.tab <- function(FD, N, ptdist, HR, p1=0.7, p2=0.5, p3=0.3){
	
sauc <- data.frame(
	NN = c(rep(NA, 4), N, NA),
  Methods = c("BNM$_P$", "BNM$_O$","TNM$_P$", "TNM$_O$", "Proposed", "Succuess"),
  P1 = c(get(paste0("F", FD, ".N", N, ".D", ptdist, ".HR", HR, ".P", p1) )$sauc.med.q13, 
         get(paste0("F", FD, ".N", N, ".D", ptdist, ".HR", HR, ".P", p1) )$succ),
	
	P2 = c(get(paste0("F", FD, ".N", N, ".D", ptdist, ".HR", HR, ".P", p2) )$sauc.med.q13, 
         get(paste0("F", FD, ".N", N, ".D", ptdist, ".HR", HR, ".P", p2) )$succ),
	
	P3 = c(get(paste0("F", FD, ".N", N, ".D", ptdist, ".HR", HR, ".P", p3) )$sauc.med.q13, 
         get(paste0("F", FD, ".N", N, ".D", ptdist, ".HR", HR, ".P", p3) )$succ)
	)[c(5,1,2,6),]
colnames(sauc) <- c("N", "Method", rep("Median (Q1, Q3)",3))

return(sauc)
}

## tsauc.tab(20,1,HR)


SAUC.tab.format <- function(
		FD=1,
		HR=1, 
		cap = "Summary of the tSAUC for Biomarker1",
		# format = ifelse(save.tex, "latex", "html"),
		fmt,
		tb.lab
		){
	
	## PTS ~ U(50,150)
DT.PT1 <- rbind(tsauc.tab(FD, 20,1,HR), tsauc.tab(FD, 30,1,HR), tsauc.tab(FD, 50,1,HR))
## PTS ~ U(50,300)
DT.PT2 <- rbind(tsauc.tab(FD, 20,2,HR), tsauc.tab(FD, 30,2,HR), tsauc.tab(FD, 50,2,HR))

DT.MK1 <- cbind.data.frame(
	Patients = c("50-150", rep(NA, nrow(DT.PT1)-1), "50-300", rep(NA, nrow(DT.PT1)-1)), 
	rbind(DT.PT1, DT.PT2))
rownames(DT.MK1) <- NULL


output <- DT.MK1 %>%
  kbl(
    caption=cap,
    format =fmt,
    # format = ifelse(save.tex, "latex", "html"),
    # format = "latex",
    longtable = F, 
    booktabs = T,
    align = "r",
    position = "!htb",
    linesep = c(rep('',3), '\\addlinespace'),
    escape = FALSE,
    label = tb.lab,) %>%
  add_header_above(c(rep("",3), "$p = 0.7$"=1, "$p = 0.5$"=1, "$p = 0.3$"=1),escape = FALSE) %>%
  footnote(general = "
			Median with 25th and 75th empirical quartiles (Q1, Q3) of the SAUC at $t=2$ are reported. 
			$N$ denotes the number of the published studies. 
			Proposed denotes the proposed sensitivity analysis method;
			BNM$_P$ denotes the HZ model using the population (published and unpublished) studies; 
			BNM$_O$ denotes the HZ model using only the observed (published) studies.
			CR denotes the proportion of convergence among 1000 repetition
			All the entries are multiplied by 100.", 
   escape = FALSE, 
			threeparttable = TRUE,  
			general_title = "")

return(output)

}
```


# Biomarker1; EXP(0.2)

```{r}
if (save.tex) sink("TB-SAUC-HR1-EXP-CR.tex")

SAUC.tab.format(
	FD=1,
	HR=1, 
	cap="Summary of the estimated SAUC for Biomarker1 when the true censoring is distributed as $Exp(0.2)$.", 
	fmt="latex",
	tb.lab = "sauc1")

if (save.tex) sink()

```


# Biomarker2; EXP(0.2)

```{r}
if (save.tex) sink("TB-SAUC-HR2-EXP-CR.tex")

SAUC.tab.format(
	FD=1,
	HR=2, 
	cap="Summary of the estimated SAUC for Biomarker2 when the true censoring is distributed as $Exp(0.2)$.", 	
	fmt="latex",
	tb.lab = "sauc2")

if (save.tex) sink()

```

# Biomarker3; EXP(0.2)

```{r}
# if (save.tex) sink("TB-SAUC-HR3-EXP-CR.tex")

SAUC.tab.format(
	FD=1,
	HR=3, 
	cap="Summary of the estimated SAUC for Biomarker3 when the true censoring is distributed as $Exp(0.2)$.", 
	fmt="latex",
	tb.lab = "sauc5")

# sink()

```


# Biomarker1; U(1,4)

```{r}
if (save.tex) sink("TB-SAUC-HR1-UNIF-CR.tex")

SAUC.tab.format(
	FD=2,
	HR=1, 
	cap="Summary of the estimated SAUC for Biomarker1 when the true censoring is distributed as $U(1,4)$, but a misspecified exponential distribution is fitted.", 	
	fmt="latex",
	tb.lab = "sauc3")

if (save.tex) sink()

```

# Biomarker2; U(1,4)

```{r}
if (save.tex) sink("TB-SAUC-HR2-UNIF-CR.tex")

SAUC.tab.format(
	FD=2,
	HR=2, 
	cap="Summary of the estimated SAUC for Biomarker2 when the true censoring is distributed as $U(1,4)$, but a misspecified exponential distribution is fitted.", 	
	fmt="latex",
	tb.lab = "sauc4")

if (save.tex) sink()

```

# Biomarker3; U(1,4)

```{r}
if (save.tex) sink("TB-SAUC-HR2-UNIF-CR.tex")

SAUC.tab.format(
	FD=2,
	HR=3, 
	cap="Summary of the estimated SAUC for Biomarker2 when the true censoring is distributed as $U(1,4)$, but a misspecified exponential distribution is fitted.", 	
	fmt="latex",
	tb.lab = "sauc6")

if (save.tex) sink()

```


