---
title: "BoxPlot-b1-N100"
author: "Yi"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.width = 5, fig.height = 5)
options(knitr.kable.NA = '')
library(knitr)
library(kableExtra)
```



## Median

Number of patients $\sim Uniform[50, 150], b = 1$

Others follows Hattori (2016).

```{r, fig.width = 10, fig.height = 5}

p <- seq(0.8, 0.2, -0.2)

load("2N100/HR1_p0.8.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med8 <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv8 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)

load("2N100/HR1_p0.6.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med6  <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv6 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)

load("2N100/HR1_p0.4.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med4  <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv4 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)

load("2N100/HR1_p0.2.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med2  <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv2 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)


x <- rbind(med8, med6, med4, med2)
matplot(x, ylim = c(0.5, 1), type = "o", ylab = "Med(SAUC)", xlab = "p", xaxt = "n", pch = 1:3)
legend("topleft", c("All studies", "Published studies", "Sensitivity analysis"), col = 1:3, lty = 1:3, pch = 1:3)

axis(1, at = 1:4, labels = seq(0.8, 0.2, -0.2))
cv <- rbind(cv8, cv6, cv4, cv2)
cv
```



```{r, fig.width = 10, fig.height = 5}

p <- seq(0.8, 0.2, -0.2)

load("2N100/HR2_p0.8.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med8 <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv8 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)

load("2N100/HR2_p0.6.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med6  <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv6 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)

load("2N100/HR2_p0.4.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med4  <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv4 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)

load("2N100/HR2_p0.2.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med2  <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv2 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)


x <- rbind(med8, med6, med4, med2)
matplot(x, ylim = c(0.5, 1), type = "o", ylab = "Med(SAUC)", xlab = "p", xaxt = "n", pch = 1:3)
legend("topleft", c("All studies", "Published studies", "Sensitivity analysis"), col = 1:3, lty = 1:3, pch = 1:3)

axis(1, at = 1:4, labels = seq(0.8, 0.2, -0.2))
cv <- rbind(cv8, cv6, cv4, cv2)
cv
```



```{r, fig.width = 10, fig.height = 5}

p <- seq(0.8, 0.2, -0.2)

load("2N100/HR3_p0.8.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med8 <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv8 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)

load("2N100/HR3_p0.6.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med6  <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv6 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)

load("2N100/HR3_p0.4.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med4  <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv4 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)

load("2N100/HR3_p0.2.RData")
sauc <- matrix(DATA[11,], ncol = 3, byrow = TRUE)
med2  <- sapply(1:3, function(i) median(sauc[,i], na.rm = TRUE))
cv  <- matrix(DATA[13,], ncol = 3, byrow = TRUE)
cv2 <- sapply(1:3, function(i) sum(1-cv[,i], na.rm = TRUE)/10)


x <- rbind(med8, med6, med4, med2)
matplot(x, ylim = c(0.5, 1), type = "o", ylab = "Med(SAUC)", xlab = "p", xaxt = "n", pch = 1:3)
legend("bottomleft", c("All studies", "Published studies", "Sensitivity analysis"), col = 1:3, lty = 1:3, pch = 1:3)

axis(1, at = 1:4, labels = seq(0.8, 0.2, -0.2))
cv <- rbind(cv8, cv6, cv4, cv2)
cv
```